### ISSUE TITLE
ROI mask

### ISSUE THREAD

**Issue by zhaogengyan** [Kamnitsask/deepmedic#100]
Hello,

I have a question related to the ROI mask. If ROI masks are provided, and default sampling is used. For each 3D patch sampled, is the entire 3D patch guaranteed within the ROI mask? Or only the center of each 3D patch is guaranteed within the ROI mask?

What if I'm not using the default sampling:
useDefaultTrainingSamplingFromGtAndRoi = False
typeOfSamplingForTraining = 3

Thank you in advance.

Best,
Gengyan

**Comment by Kamnitsask** [comment]
Hi Gengyan,

Sorry for the delay in replying this. Hey! You are my 100th issue! We better deal with it nicely! :p

No, when sampling, it's the central one that is guaranteed to be within the ROI. That's the same for all types of sampling 0/1/2/3.

Is there a specific reason you would want the whole patch contained? If so, a small change (a couple of lines?) in the code may be sufficient to change this behaviour.

K

**Comment by zhaogengyan** [comment]
Thank you very much, Konstantinos. I just want to know the configuration. Thanks again.

Best,
Gengyan
