### ISSUE TITLE
Running on windows

### ISSUE THREAD

**Issue by samieti02** [Kamnitsask/deepmedic#110]
Hi Sir,

please can you give us the steps on how you run it on windows?
I am not an expert with the command prompt. Ive installed everything, created and activated the environment, but when I try to run the command 
**<condaEnv_dm> C:\Users\Me\AnacondaProjects\DeepMedicMaster>deepMedicRun**
I got the error the commmand ist not correct written

I also tried the commands: conda deepMedicRun  oder deepMedicRun -h. 
I get the errors CommandNotFoundError

Can you please, help us ?
Thank you

**Comment by Kamnitsask** [comment]
Hello,

I am sorry, but this issue, together with the accompanying email, seem to point that you need to familiarize yourself a bit with the Windows OS and its command prompts. The current issue is not an issue of this project (the code does run on Windows), but rather a more generic Windows-usage enquiry. I am sorry but I cannot provide much feedback/guidance on this. My suggestion is to give yourself some time, google stuff and get familiar with the Windows OS, and then try again.

Kind regards,
Kostas
