### ISSUE TITLE
Problem with Validation: Process Killing itself

### ISSUE THREAD

**Issue by adamshephard** [Kamnitsask/deepmedic#112]
Hi Kostas,

First of all thanks for sharing this excellent tool, it's yielded some really good results on my data so far.

However, I have been unable to get the validation to work on any of my data or the original BRATS data set. After 5 epochs, when validation starts, the training process automatically kills itself. I've read previously about there being a memory error, do you have any suggestion as to how I can fix this problem? (The problem does not occur when I remove validation.)

Below is the output to terminal:

+++++++++++++++++++++ Reporting Segmentation Metrics for the subject #0 ++++++++++++++++++++++++++
ACCURACY: (Validation) The Per-Class DICE Coefficients for subject with index #0 equal: DICE1=[ 0.8856 0.1148 0.8573 0.0594 0.6986 ] DICE2=[ 0.8870 0.1295 0.8573 0.0594 0.6986 ] DICE3=[ 0.8873 0.1295 0.8576 0.0594 0.6986 ]
EXPLANATION: DICE1/2/3 are lists with the DICE per class. For Class-0, we calculate DICE for whole foreground, i.e all labels merged, except the background label=0. Useful for multi-class problems.
EXPLANATION: DICE1 is calculated as segmentation over whole volume VS whole Ground Truth (GT). DICE2 is the segmentation within the ROI vs GT. DICE3 is segmentation within the ROI vs the GT within the ROI.
EXPLANATION: If an ROI mask has been provided, you should be consulting DICE2 or DICE3.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~ Segmenting subject with index #1 ~~~~~~~~~~~~~~~~~~~~
Loading subject with 1st channel at: /home/adamshephard/nu69/DeepMedic/examples/dataForExamples/brats2015TrainingData/validation/brats_2013_pat0004_1/Flair_subtrMeanDivStd.nii.gz
Starting to (tile) extract Segments from the images of the subject for Segmentation...
Finished (tiling) extracting Segments from the images of the subject for Segmentation.
Starting to segment each image-part by calling the cnn.cnnTestModel(i). This part takes a few mins per volume...
Total number of Segments to process:200
Processed 0/200 Segments.
Killed

Thanks for your help.

Kind regards,
Adam

**Comment by Kamnitsask** [comment]
Hello and sorry for the slow reply.

I would guess indeed that this is a memory issue. But segmentation should be cheap, except if you changed something in the configuration, or something weird happens.

- How much RAM / GPU memory your system has?
- Which version of DM are you using? (can be seen in setup.py).
- Have you changed something in the configuration? (anything could be a hint)
- Have you specified in the config for the process to save feature maps? Cause if you specify it to do that with too many FMs, they can indeed occupy the memory.

**Comment by adamshephard** [comment]
I'm currently running it using a High Performance Computing facility which gives me access to GPU nodes with 128GB RAM or 256GB RAM per node and the version I am using is 0.6.1.

The only things that I have changed in the configuration files are the folders for output and with regards to the feature maps, the feature maps section is omitted in the original trainConfig file, so I assume that that is not the issue? But it is strange, as the model works perfectly when validation is not included. However, the section for segmentation and probability maps for each class are set to True: 

#[Optionals] Specify whether to save the segmentation and probability maps for each class. Default: True to all
saveSegmentationVal = True
saveProbMapsForEachClassVal = [True, True, True, True, True]

Could this be part of the memory issue?

Thanks again for your help,
Adam

**Comment by Kamnitsask** [comment]
Hm, then it can be something weird.

The saveSegm /saveProbMaps do not influence memory. With them false, the same computations are done, but results are not saved.

HPC machines may have some "interesting" configurations, that may be killing it for some weird reason.

For diagnostic purposes, could you run DeepMedic on a desktop of yours with a GPU?
You don't need to train it. The validation process that is killed in the above point is exactly the same running when you do -test. So, could you create a model, randomly initialized, non trained, and just -test with it on a local desktop, to check if it works? If it does, it will point show us that it may be something with the configuration of the HPC.

$ ./deepMedicRun -newModel /path/to/model/config
$ ./deepMedicRun -test /path/to/test/config -model /path/to/model/created/from/above/command -dev cuda0

Just put in the test config the same files/channels as in your validation dataset, to try on the same files that it gets killed on.

Please try the above -test also on the HPC. It should be killed.

K

**Comment by adamshephard** [comment]
Hi,

Apologies for the slow reply.

I'm unable to do the first part of the test as I don't have a desktop available to use with a GPU. However, upon creating and testing the model on the validation data set, the process actually works and is not killed. Very strange... However, the original problem still persists.

Kind regards,
Adam

**Comment by Kamnitsask** [comment]
This is probably quite a forgotten issue, but I may have found something relevant:

In commit 5f37bcc I found and fixed an issue that did not let the RAM of volumes loaded to be efficiently released during training/validation.

This has been causing more RAM to be required than what was intended.

Now RAM consumption should be significantly decreased.

Perhaps this was related to your problem.

Kind regards,
Kostas

**Comment by adamshephard** [comment]
Great, I will look into downloading the new commit and testing it further!

Thanks again for your help,
Adam
