### ISSUE TITLE
negative output size after the 5th convolution [downsampled pathway]

### ISSUE THREAD

**Issue by YilinLiu97** [Kamnitsask/deepmedic#113]
Hi @Kamnitsask, thanks for the great work.  I'm calculating the receptive field and output size of the second pathway - the downsampled one, and found:

> layer output sizes given image = 27x27
************net structrue name is deepmedic**************
Layer Name = conv1, Output size =   9, Stride =   3, RF size =   3
Layer Name = conv2, Output size =   7, Stride =   3, RF size =   9
Layer Name = conv3, Output size =   5, Stride =   3, RF size =  15
Layer Name = conv4, Output size =   3, Stride =   3, RF size =  21
Layer Name = conv5, Output size =   1, Stride =   3, RF size =  27
Layer Name = conv6, Output size =  -1, Stride =   3, RF size =  33
Layer Name = conv7, Output size =  -3, Stride =   3, RF size =  39
Layer Name = conv8, Output size =  -5, Stride =   3, RF size =  45
Layer Name = fc_conv1, Output size =  -5, Stride =   3, RF size =  45
Layer Name = fc_conv2, Output size =  -5, Stride =   3, RF size =  45
Layer Name = 1x1x1_conv, Output size =  -5, Stride =   3, RF size =  45

I'm wondering how do you handle the negative output size after the 5th convolutions without padding? thanks.

**Comment by YilinLiu97** [comment]
I also found that when I removed the second pathway the performance becomes bad - not even close to a reasonable output. I'm surprised that the second pathway makes that much difference. I'm wondering did you do the same thing and observe something similar? thanks!

**Comment by Kamnitsask** [comment]
Negative output size should not happen, and is not handled.
Where did this above calculation come from? 

I notice there is "stride=3" mentioned in your message. Note that DM never uses stride, it is always assumed 1 for all convs. And the code is not made to handle strided convs. So, possibly that's part of the problem. If you wish to put that in there, you ll have to adapt a few parts of the code I guess.

Regarding the secondary pathways, depending on the task, their effect can be massive or small. Eg by default, second pathway shows x3 the context to the net. The effect can be huge, eg the default resolution is very high and the primary pathway sees too little context as a result.

Sorry for the late reply, hope this clarifies things.
K
