### ISSUE TITLE
Theano error during training

### ISSUE THREAD

**Issue by CarlosUziel** [Kamnitsask/deepmedic#114]
Dear all,
I'm using DeepMedic as part of my MSc Dissertation to segment the ISLES 2017 data, so first of all I thank you for making DeepMedic available and with such nice instructions to facilitate its use.

To the matter at hand, I'm having a problem with Theano throwing an exception during training, the error is shown in the file attached (_theano_error.txt_). I'm also attaching the full output of a training session (_output_with_error.txt_) plus the configuration files I'm using (_modelConfig.txt_, _trainConfig.txt_).

[output_with_error.txt](https://github.com/Kamnitsask/deepmedic/files/2087637/output_with_error.txt)
[theano_error.txt](https://github.com/Kamnitsask/deepmedic/files/2087638/theano_error.txt)
[modelConfig.txt](https://github.com/Kamnitsask/deepmedic/files/2087644/modelConfig.txt)
[trainConfig.txt](https://github.com/Kamnitsask/deepmedic/files/2087645/trainConfig.txt)

This error seems to happen rather randomly, but always during the training on segments phase.

I'm using two different computers at the moment:

- **PC0:** 16GB RAM and 1070 Ti (8GB). Ubuntu 17.10.
- **PC1:** 8GB RAM and GK110 TITAN (6GB). Ubuntu 16.04.

While I initially had the same problem in both computers, reducing the segment size to patch size, [17,17,17], and using a batch of 32 on PC0 allowed me to complete a full training run. However, a segment size of [17,17,17] and a batch size of as little as 4 didn't avoid the error in PC1. The error and output I've posted are therefore from PC1.

Given the information above, my guess is that this error is memory related, but I can't be sure because the thrown error doesn't seem to mention any of that, or maybe it does implicitly and I'm not understanding it. Even so, I can't be sure if it's either the RAM of the GPU memory. It specially annoys me is the fact that the error is thrown "randomly", never in a specific epoch or subepoch, so it's more difficult to trace its nature.

It is worth mentioning that both deepMedic and tinyCNN examples run flawlessly in GPU. Also, I'm using deepmedic-0.6.1.

If you need more information, please do not hesitate to ask further.

Thanks a lot.

**Comment by Kamnitsask** [comment]
Hello there, sorry for the error.

These Theano-errors are quite a thing to debug.

From the error, I see nothing that indicates it's a memory problem. Especially on the 16GB RAM you should not get a memory problem (provided that you dont run anything else on it). 
> You can check if it's memory error by running the process, and do "htop" in unix, and then keep on looking for a few minutes the memory bar, to check if it ever goes up to 16GB/8GB.

The line in the error that attracted my attention is:
```
IndexError: index 2 is out of bounds for axis 1 with size 2
Apply node that caused the error: AdvancedIncSubtensor{inplace=False,  set_instead_of_inc=False}(HostFromGpu(gpuarray).0, Assert{msg='`x[i]` and `y` do not have the same shape.'}.0, TensorConstant{[[[[0]]]
```
Something in the code tries to grab index array[2] when array has only 2 elements.

I remember getting such an error during training when I would (by mistake) use a model with 2 output classes while in the Ground Truth labels there would be more than 2 classses (ie, pixels with values >=2).

My assumption is that, in your GT labels there are voxels with value >1, while you specify a network with only 2 classes. And by going at segment_size = [17,17,17], (eg only 32 voxels per batch when batch-size =32), than with a large segment, and so you randomly hit those >1 GT voxels less frequently.

Before we look into anything further, do me a big favor for diagnosis:
1. Can you change your modelConfig to have 3 classses? Or more, eg 5. Does not matter if more, less is problem. And then run the same training process. If it does not break, it indicates I may be right in the above.
2. You can also right a script and go over your whole database, and do a check if any voxel in any ground-truth label nii has a value >1. If yes, then this is your problem. You ll need in modelConfig a net with >2 classes.

Let me know if you try any of these, and I ll try to advice after that.

K

**Comment by CarlosUziel** [comment]
Hello again,

Your intuition was right, my GT labels weren't binary, as they were supposed to be. The problem originated during the resampling/registration step of my data preprocessing script. I was using continuous interpolation for all sequences, but GT label sequences need nearest neighbour interpolation instead.

I expect this will fix the problem, I will run the network asap and let you know if it's still not working.

Thank you very much.
