### ISSUE TITLE
Trun off batch normalization

### ISSUE THREAD

**Issue by NinaJacobsen** [Kamnitsask/deepmedic#116]
Hi.

I would like to turn off batch normalization completely to do some tests of the network. Is it doable to do this by setting rollAverageForBNOverThatManyBatches = 0 in the model config, or do i have a set some variable in the code?

Thanks,
N. Jacobsen

**Comment by Kamnitsask** [comment]
Indeed you can turn off BN by passing a value 0 or negative to the value rollAverageForBNOverThatManyBatches in modelConfig.

I have now added a note in the modelConfig to indicate this.

Thank you
