### ISSUE TITLE
GAN add on to DeepMedic

### ISSUE THREAD

**Issue by NinaJacobsen** [Kamnitsask/deepmedic#117]
Hi Kamnitsas.

Daniel Rueckert presented some work of yours related to a GAN add on the to deepmedic i order to overcome issues using the network to segment structures in unseen datasets which differ a lot from the training dataset. Can you comment on whether this piece of code be pushed in this branch? It would be very much appreciated. I see, that the work was submitted to arxiv in 2016, but I dont seem to be able to find the source code. https://arxiv.org/abs/1612.08894 

Thanks,
N.Jacobsen.

**Comment by Kamnitsask** [comment]
Sorry, not there yet. It had to be postponed until the backend was changed to Tensorflow from Theano (cause of end of developent of the latter). Theano to TF transfer was completed in v0.7.0. The adversarial feature is going to be the next big development iteration, but it cannot be worked on before September'18. Too many things I have to take care of till then. Sorry for the delay.

Closing this issue, as it's related to my open issue #39 .

Again sorry for the delay. I see this project more than pushing out code, but rather a (hopefully) well validated, continuously evolving system, so every addition to it takes much longer than expected.

K
