### ISSUE TITLE
Version of Tensorflow?

### ISSUE THREAD

**Issue by ck37** [Kamnitsask/deepmedic#121]
Hello,

Can you please clarify which version of Tensorflow is expected by Deepmedic? I was not able to find that noted in the documentation anywhere.

Thanks,
Chris

**Comment by Kamnitsask** [comment]
Hello,

Good question, sorry for missing this. I can't remember currently what's the minimum required. I ve been using 1.8 the last few months. I will try to find time to go backwards and check what's the minimum and update the docs.

**Comment by ck37** [comment]
Thanks, even just having 1.8 as a recommended version is helpful - appreciate it.

**Comment by Kamnitsask** [comment]
Added a note in readme under (Sec 1.1 Required libraries) about latest versions tested.

As of Febr 2019, v0.7.1 of DM was tested using:

Python 3.5.2
Tensorflow 1.12.0
nibabel 2.3.3
numpy 1.16.1

Thanks a lot, closing.
