### ISSUE TITLE
make ground truth

### ISSUE THREAD

**Issue by littleapril** [Kamnitsask/deepmedic#124]
Hello Sir,
I want to know how your ground truth was made, can you tell me?

Thanks

**Comment by ChaitanyaBaweja** [comment]
It depends upon the dataset you use. Deepmedic was initially tested for BraTs and ISLES(http://www.isles-challenge.org/). Later on with UKBB as well. All these datasets come with GT labels. In most cases, these labels are created using manual segmentation by radiologists but many times some automated tools are used.  You can read this for more info about UKBB dataset(https://www.ncbi.nlm.nih.gov/pubmed/29079522).

**Comment by littleapril** [comment]
Thanks

**Comment by samieti02** [comment]
The data are also provided by the organizer of the Brats challenge. They actually doesnt give details about how they annotate the data.
You can have a look at their paper 

> Menze et al., The Multimodal Brain TumorImage Segmentation Benchmark (BRATS), IEEE Trans. Med. Imaging, 2015
