### ISSUE TITLE
./deepMedicRun -h

### ISSUE THREAD

**Issue by Alexfengbowen** [Kamnitsask/deepmedic#130]
I build the framework and train the small CNN in the Windows7, but when I executed the command “./deepMedicRun -h” , there is a prompt ，“.” is not a internal command or external commands，nor executable program or batch file. Could you please tell me how to solve this?

**Comment by Kamnitsask** [comment]
This is a windows message that tells you that you didnt run the command correctly I believe.

If you ve run the ./deepMedicRun for training a small cnn, it means that you ve set up things ok. Just add the -h and you should get the help.

This should like a small mistake in the usage of windows command line I think.

**Comment by Alexfengbowen** [comment]
Thank you very much for your kindness, this question (unrecognized character ".") has been solved on another machine, although I don't know the principle. Under the guidance of your instructions, I have trained a model based on the data set you gave.
