### ISSUE TITLE
Data Pre-Processing

### ISSUE THREAD

**Issue by littleapril** [Kamnitsask/deepmedic#134]
Hi Kamnitsask,
I have some question about this network.
In section 1.4, the second step,I don't known “ other images of each subject need to be co-registered (per-subject, no need for inter-subject registration)”，Can you explain what other images mean? If I want to process my data, what can I do?

**Comment by Kamnitsask** [comment]
Hello, thank you very much for your interest littleapril.

Please see replies to previous issues #56 , #72 , #19 , #95 issues regarding noralization, and the description in our papers.

Thank you!
Kostas
