### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by littleapril** [Kamnitsask/deepmedic#135]
Hi Kamnitsask,
I used my own data to train the network, but the following errors occurred:

ERROR: Caught exception from main process: list index out of range
Traceback (most recent call last):
  File "./deepMedicRun", line 178, in <module>
    session.run_session(sess_device, model_params, args.reset_trainer)
  File "/home/zhaomo/cx/deepmedic/deepmedic/frontEnd/trainSession.py", line 158, in run_session
    do_training( *( [sessionTf, saver_all, cnn3d, trainer] + self._params.get_args_for_train_routine() ) )
  File "/home/zhaomo/cx/deepmedic/deepmedic/routines/training.py", line 357, in do_training
    reflectImageWithHalfProbDuringTraining
  File "/home/zhaomo/cx/deepmedic/deepmedic/dataManagement/sampling.py", line 199, in getSampledDataAndLabelsForSubepoch
    gtLabelsForTheCentralPredictedPartOfSegmentsInGpUForSubepoch )
  File "/home/zhaomo/cx/deepmedic/deepmedic/dataManagement/sampling.py", line 593, in shuffleTheSegmentsForThisSubepoch
    shuffledGtLabelsForTheCentralPredictedPartOfSegmentsInGpUForSubepoch = shuffledInputListsToZip[numOfPathwayWithInput]
IndexError: list index out of range

Can you help me?

Thanks
April

**Comment by Kamnitsask** [comment]
Hello April,

This function is constantly called and it's the first time I see it breaking. It seems the process did not manage to extract input segments for each of the pathways.

I cannot help if I dont have more details about what you have done.

Have you changed the architecture in modelConfig?
What have you changed in the trainingConfig?
Can you please make sure that you are passing correctly the image channels / masks / ground truth labels in the training config? If you have not changed the architecture in modelConfig, I suspect you are doing something wrong when passing the image paths to trainConfig.

Let me know how this goes.

K

**Comment by littleapril** [comment]
Hi Kamnitsask,
It seems that my path did not enter the right questions. I am really sorry.

Thanks

**Comment by Kamnitsask** [comment]
No problem, glad you find the problem.
