### ISSUE TITLE
problem of data pre-peocessing 

### ISSUE THREAD

**Issue by JayGou** [Kamnitsask/deepmedic#137]
Hi,Kamnitsask.
    I have some confusion about Brats2015 data processing.
    I know I should get the mean and std within the RoI, then I should do (data - mean)/std in the whole image.
    But when I have done that, I find I get error messages by running the code.
    Can you do me a favor? Thank you very much.

**Comment by Kamnitsask** [comment]
Hello JayGou,

What kind of errors are you getting?

Just doing the normalization should do nothing that can be raising errors. Worst case scenario, if not done right, segmentation will not be great, but not get errors.

I would need a better explanation of your problem and errors to be able to help.
