### ISSUE TITLE
Overffiting on ISLES2015_SISS Dataset

### ISSUE THREAD

**Issue by ZeinabSalkhorde** [Kamnitsask/deepmedic#139]
Hi
Dear Mr. Konstantinos
Thank you for sharing the work of Deepmedic. I am working Ischemic Stroke Lesion segmentation by using original deepMedicOriginal on ISLES2015_SISS database. I used the following modelconfig.cfg, trainconfig.cfg and testconfig.cfg:

---------------------------------modelconfig.cfg---------------------------------------------
#Default values are set internally, if the corresponding parameter is not found in the configuration file.

#[Optional but highly suggested] The name will be used in the filenames when saving the model.
#Default: "cnnModel"
modelName = "deepMedicOriginal"

#[Required] The main folder that the output will be placed.
folderForOutput = "../../../output/"

#================ MODEL PARAMETERS =================

#[Required] The number of classes in the task. Including background!
numberOfOutputClasses = 2
#[Required] The number of input channels, eg number of MRI modalities.
numberOfInputChannels = 4

#+++++++++++Normal pathway+++++++++++
#[Required] This list should have as many entries as the number of layers I want the normal-pathway to have.
#Each entry is an integer that specifies the number of Feature Maps to use in each of the layers.
numberFMsPerLayerNormal = [40, 40, 40, 40, 40, 40, 80, 80]
#[Required] This list should have as many entries as the number of layers in the normal pathway.
#Each entry should be a sublist with 3 entries. These should specify the dimensions of the kernel at the corresponding layer.
kernelDimPerLayerNormal = [[3,3,3], [3,3,3], [3,3,3], [3,3,3], [3,3,3], [3,3,3], [3,3,3], [3,3,3]]

#[Optional] List with number of layers, at the output of which to make a residual connection with the input of the previous layer. Ala Kaiming He et al, "Deep Residual Learning for Image Recognition".
#Note: Numbering starts from 1 for the first layer, which is not an acceptable value (no previous layer).
#Example: [4,6,8] will connect (add) to the output of Layer 4 the input of Layer 3. Also, input to 5th will be added to output of 6th, and input of 7th to output of 8th.
#Default: [], no residual connections
layersWithResidualConnNormal = []

#[Optional] Layers to make of lower rank. Ala Yani Ioannou et al, "Training CNNs with Low-Rank Filters For Efficient Image Classification".
#Example: [3,5] will make the 3rd and 5th layers of lower rank.
#Default: []
lowerRankLayersNormal = []

#+++++++++++Subsampled pathway+++++++++++
#[Optional] Specify whether to use a subsampled pathway. If False, all subsampled-related parameters will be read but disregarded in the model-construction.
#Default: False
useSubsampledPathway = True

#[Optionals] The below parameters specify the subsampled-pathway architecture in a similar way as the normal.
#If they are ommitted and useSubsampledPathway is set to True, the subsampled pathway will be made similar to the normal pathway (suggested for easy use).
#[WARN] Subsampled pathway MUST have the same size of receptive field as the normal. Limitation in the code. User could easily specify different number of FMs. But care must be given if number of layers is changed. In this case, kernel sizes should also be adjusted to achieve same size of Rec.Field.
numberFMsPerLayerSubsampled = [15, 15, 15, 15, 15, 15, 30, 30]
kernelDimPerLayerSubsampled = [[3,3,3], [3,3,3], [3,3,3], [3,3,3], [3,3,3], [3,3,3], [3,3,3], [3,3,3]]

#[Optional] How much to downsample the image that the subsampled-pathway processes.
#Default: [3,3,3]
subsampleFactor = [3,3,3]

#[Optional] Residual Connections for subsampled pathway. See corresponding parameter for normal pathway.
#Default: mirrors the normal pathway, no residual connections
#layersWithResidualConnSubsampled = []

#[Optional] Layers to make of lower rank. See corresponding parameter for normal pathway.
#Default: Mirrors the normal pathway
#lowerRankLayersSubsampled = []

#+++++++++++FC Layers+++++++++++
#[Optional] After the last layers of the normal and subsampled pathways are concatenated, additional Fully Connected hidden layers can be added before the final classification layer.
#Specify a list, with as many entries as the number of ADDITIONAL FC layers (other than the classification layer) to add. The entries specify the number of Feature Maps to use.
#Default: []
numberFMsPerLayerFC = [150, 150]

#[Optional] Specify dimensions of the kernel in the first FC layer. This kernel combines the features from multiple scales. Applies to the final Classification layer if no hidden FC layers in network.
#Note: convolution with this kernel retains the size of the FMs (input is padded).
#Default: [1,1,1]
kernelDimFor1stFcLayer = [1,1,1]

#[Optional] Residual Connections for the FC hidden layers. See corresponding parameter for normal pathway.
#Default: [], no connections.
#layersWithResidualConnFC = []

#+++++++++++Size of Image Segments+++++++++++
#DeepMedic does not process patches of the image, but larger image-segments. Specify their size here.

#[Required] Size of training segments influence the captured distribution of samples from the different classes (see DeepMedic paper)
segmentsDimTrain = [25,25,25]
#[Optional] The size of segments to use during the validation-on-samples process that is performed throughout training if requested.
#Default: equal to receptive field, to validate on patches.
segmentsDimVal = [17,17,17]
#[Optional] Bigger image segments for Inference are safe to use and only speed up the process. Only limitation is the GPU memory.
#Default: equal to the training segment.
segmentsDimInference = [45,45,45]

#+++++++++++Batch Sizes+++++++++++
#[Required] The number of segments to create a batch.
#The samples in a training-batch are all processed and one optimization step is performed.
#Larger batches approximate the total data better and should positively impact optimization but are computationally more expensive (time and memory).
batchSizeTrain = 10
#[Optionals] Batch sizes for validation and inference only influence the speed. The bigger the better. Depends on the segment size and the model size how big batches can be fit in memory.
#Default: Equal to train-batch size.
batchSizeVal = 48
batchSizeInfer = 10

#[Optionals] Dropout Rates on the input connections of the various layers. Each list should have as many entries as the number of layers in the corresponding pathway.
# 0 = no dropout. 1= 100% drop of the neurons. Empty list for no dropout.
#Default: []
dropoutRatesNormal = []
dropoutRatesSubsampled = []
#Default: 50% dropout on every Fully Connected layer except for the first one after the concatenation
#Note: The list for FC rates should have one additional entry in comparison to "numberFMsPerLayerFC", for the classification layer.
dropoutRatesFc = [0.0, 0.5, 0.5] # +1 for the classification layer!

#[Optional] Initialization method of the kernel weights. Specify 0 for classic, from the normal distribution N(0, 0.01). Otherwise specify 1 for the method of He et al from "Delving Deep into Rectifiers".
#Default: 1
initializeClassic0orDelving1 = 1
#[Optional] Activation Function for all convolutional layers. Specify 0 for ReLU, 1 for PreLU.
#Default: 1
relu0orPrelu1 = 1

#[Optional] Batch Normalization uses a rolling average of the mus and std for inference. Specify over how many batches (optimization steps) this rolling average should be taken. 
#Default : 60
rollAverageForBNOverThatManyBatches = 60

--------------------------------------------trainconfig.cfg------------------------------------------------

#Default values are set internally, if the corresponding parameter is not found in the configuration file.

#[Optional but highly suggested] The name will be used for saving the models,logs and results.
#Default: "trainSession"
sessionName = "trainSessionDeepMedicOriginal"

#[Required] The main folder that the output will be placed.
folderForOutput = "../../../output/"

#[Optional] The path to the saved CNN-model to use for training. Optional in the case the the model is specified from command line with the -model option. In this case, this entry file of the config file will be disregarded, and the one from the command line will be used.
cnnModelFilePath = "../../../output/models/placeholder"

#=======================Training=====================================

#+++++++++++Input+++++++++++

#[Required] A list that should contain as many entries as the channels of the input image (eg multi-modal MRI). The entries should be paths to files. Those files should be listing the paths to the corresponding channels for each training-case. (see example files).
channelsTraining = ["./trainChannels_Flair.cfg", "./trainChannels_DWI.cfg","./trainChannels_T2.cfg","./trainChannels_T1.cfg"]

#[Required] The path to a file which should list paths to the Ground Truth labels of each training case.
gtLabelsTraining = "./trainGtLabels.cfg"

#+++++++++++Sampling+++++++++++

#[Optional] The path to a file, which should list paths to the Region-Of-Interest masks for each training case.
#If ROI masks are provided, under default-sampling settings, the training samples will be extracted only within it. Otherwise from whole volume.
#This mask is also used for calculating mu and std intensities for intensity-augmentation, if performed.
roiMasksTraining = "./trainRoiMasks.cfg"

#+++++++++++Advanced Sampling+++++++++++
#Note: Given variables in this "Advanced Sampling" section are disregarded if default settings are used, unless one sets: useDefaultTrainingSamplingFromGtAndRoi = False.

#[Optional] True in order to use default sampling for training. In this case, foreground samples are extracted from within the GT mask.
#Background samples are then extracted from the ROI (or full volume), excluding the GT. By default, equal number of samples are extracted from foreground and background.
#Note: Advanced options are disabled if default settings are used.
#Default: True
useDefaultTrainingSamplingFromGtAndRoi = True

#[Optional] Type-of-Sampling to use for training. 
#[Possible Values] 0 = Foreground / Background, 1 = Uniform, 2 = Full Image , 3 = Separately-Per-Class.
#Note: In case of (2) Full Image, ensure you provide segmentsDimTrain in modelConfig.cfg at least as big as image dimensions (+CNN's receptive field if padding is used).
#Default: 0
typeOfSamplingForTraining = 0

#[Optional] List the proportion (0.0 to 1.0) of samples to extract from each category of samples.
#Note: Depending on the Type-of-Sampling chosen, list must be of the form:
#	>> Fore/Background: [proportion-of-FOREground-samples, proportion-of-BACKground-samples], eg [0.3, 0.7]. IMPORTANT: FOREground first, background second!
#	>> Uniform or Full-Image: Not Applicable and disregarded if given.
#	>> Separate sampling of each class: [proportion-of-class-0(background), ..., proportion-of-class-N]
#Note: Values will be internally normalized (to add up to 1.0).
#Default: Foreground/Background or Separately-Each-Class : equal number of segments extracted for each of the categories. Uniform or Full-Image: N/A
proportionOfSamplesToExtractPerCategoryTraining = [0.5, 0.5]

#[Optional] This variable allows providing weighted-maps to indicate where to extract more segments for each category of samples. Higher weight means more samples from that area.
#The value provided should be a List with paths to files. As many files as the categories of samples for the chosen Sampling-Type.
#Similarly to the files listing the Ground Truth, Channels, etc per subject, these files should list the paths to the weight-maps of each subject for the corresponding category.
#Note: Number of files required: Fore/Backgr:2, Uniform:1, Full-Image:N/A, Separate each class:NumOfOutputClasses (Incl Backgr).
#IMPORTANT: Sequence of weight-maps is important!
#>> If Fore/Background type of sampling, provide for the FOREground first!
#>> If Separately sampling each class, provide weightmap-files in the same sequence as the class-labels in your Ground Truth! Eg background-0 first, class-1 second, etc.
#Default : If this variable is not provided, samples are extracted based on the Ground-Truth labels and the ROI. 
#weightedMapsForSamplingEachCategoryTrain = ["./weightMapsForeground.cfg", "./weightMapsBackground.cfg"]

#+++++++++++Training Cycle (see documentation)+++++++++++

#[Optionals but highly suggested as they are model dependent.]
#How many epochs to train for. Default: 35
numberOfEpochs = 35
#How many subepochs comprise an epoch. Every subepoch I get Accuracy reported. Default: 20
numberOfSubepochs = 20
#Every subepoch, load the images from that many cases and extract new training samples. Default: 50
numOfCasesLoadedPerSubepoch = 50
#Every subepoch, extract in total this many segments and load them on the GPU. Memory Limitated. Default: 1000
#Note: This number in combination with the batchSizeTraining, define the number of optimization steps per subepoch (=NumOfSegmentsOnGpu / BatchSize).
numberTrainingSegmentsLoadedOnGpuPerSubep = 1000

#+++++++++++Learning Rate Schedule+++++++++++

#[Optional] The type of schedule to use for Learning Rate annealing.
#0=Stable Decrease. 1=Auto (Lower LR when validation accuracy plateaus. Requires validation-on-samples). 2=Lower at predefined epochs. 3=Exponentially decrease LR, linearly increase Mom.
#Note: Training Schedule is very important. We suggest running stable and observing training error, then lower LR when it plateaus. Otherwise, use exponential but make sure to train for enough epochs.
stable0orAuto1orPredefined2orExponential3LrSchedule = 2

#[For Stable + Auto + Predefined] By how much to divide LR when lowering. Default: 2
whenDecreasingDivideLrBy = 2.0

#[For Stable + Auto] How many epochs to wait before decreasing again. Set Zero to never lower LR. Default: 3
#numEpochsToWaitBeforeLoweringLr = 3
#[For Auto] If validation accuracy increases more than this much, reset the waiting counter. Default: 0.0005
#minIncreaseInValidationAccuracyThatResetsWaiting = 0.0005

#[Required for Predefined] At which epochs to lower LR.
predefinedSchedule = [12, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46]

#[Required for Exponential] [First epoch to start lowering from, value for LR to reach at last epoch, value for Mom to reach at last epoch]
exponentialSchedForLrAndMom = [12, 1.0/(2**(7)), 0.9]

#+++++++++++Data Augmentation+++++++++++

#[Optional] Specify whether to reflect the images by 50% probability in respect to the X/Y/Z axis. Default: [False, False, False]
reflectImagesPerAxis = [True,False,False]

#[Optional] Augmentation by changing the mean and std of training samples. Default: False
performIntAugm = False
#I' = (I + shift) * multi
#[Optionals] We sample the "shift" and "multi" variable for each sample from a Gaussian distribution. Specify the mu and std.
#Defaults : [0, 0.1] and [1.,0.]
sampleIntAugmShiftWithMuAndStd = [0, 0.1]
sampleIntAugmMultiWithMuAndStd = [1., 0.0]

#+++++++++++Optimization+++++++++++
#[Optionals]
#Initial Learning Rate. Default: 0.001.
learningRate = 0.001
#Optimizer to use. 0 for classic SGD, 1 for Adam, 2 for RmsProp. Default: 2
sgd0orAdam1orRms2 = 2
#Type of momentum to use. 0 for standard momentum, 1 for Nesterov. Default: 1
classicMom0OrNesterov1 = 1
#Momentum Value to use. Default: 0.6
momentumValue = 0.6
#Non-Normalized (0) or Normalized momentum (1). Bear in mind that Normalized mom may result in smaller gradients and might need relatively higher Learning Rate. Default: 1
momNonNorm0orNormalized1 = 1
#Parameters for RmsProp. Default: rho=0.9, e=10**(-4) (1e-6 blew up the gradients. Haven't tried 1e-5 yet).
rhoRms = 0.9
epsilonRms = 10**(-4)

#[Optionals] Regularization L1 and L2.
#Defaults: L1_reg = 0.000001, L2_reg = 0.0001
L1_reg = 0.000001
L2_reg = 0.0001

#+++++++Freeze Layers++++++
#[Optional] Specify layers the weights of which you wish to be kept fixed during training (eg to use weights from pre-training). First layer is 1.
# One list for each of the normal, subsampled, and fully-connected (as 1x1 convs) pathways. For instance, provide [1,2,3] to keep first 3 layers fixed. [] or comment entry out to train all layers.
# Defaults: [] for the Normal and FC pathway. For the Subsampled pathway, if entry is not specified, we mirror the option used for the Normal pathway. 
layersToFreezeNormal = []
layersToFreezeSubsampled = []
layersToFreezeFC = []

#==================Validation=====================

#[Optionals] Specify whether to perform validation on samples and full-inference every few epochs. Default: False for both.
performValidationOnSamplesThroughoutTraining = True
performFullInferenceOnValidationImagesEveryFewEpochs = True

#[Required] Similar to corresponding parameter for training, but points to cases for validation.
channelsValidation = ["./validation/validationChannels_Flair.cfg", "./validation/validationChannels_DWI.cfg","./validation/validationChannels_T2.cfg","./validation/validationChannels_T1.cfg"]

#[Required for validation on samples, optional for full-inference] Similar to corresponding parameter for training, but points to cases for validation.
gtLabelsValidation = "./validation/validationGtLabels.cfg"

#[Required] Similar to corresponding parameter for training. Only influences how accurately the validation samples will represent whole data. Memory bounded.
#Default: 3000
numberValidationSegmentsLoadedOnGpuPerSubep = 5000

#[Optional] Similar to corresponding parameter for training
roiMasksValidation = "./validation/validationRoiMasks.cfg"

#+++++Advanced Validation Sampling+++++:
#Note: Given variables in this "Advanced Validation Sampling" section are disregarded if default settings are used, unless one sets: useDefaultUniformValidationSampling = False.

#[Optional] True in order to use default sampling for validation. Default is uniform sampling within the ROI (or whole volume if not provided).
#Note: Advanced options are disabled if default settings are used.
#Default: True
useDefaultUniformValidationSampling = True

#[Optional] Type-of-Sampling to use for Validation. See description of corresponding variable for training.
#Default: 1 (uniform sampling)
typeOfSamplingForVal = 1

#[Optional] List the proportion (0.0 to 1.0) of samples to extract from each category of samples. See description of corresponding variable for training.
#Default: Foreground/Background or Separately-Each-Class : equal number of segments extracted for each of the categories. Uniform or Full-Image: N/A
#proportionOfSamplesToExtractPerCategoryVal = [0.3, 0.7]

#[Optional]
#The following variable allows providing weighted-maps that indicate where to acquire more samples for each category/class. See description of corresponding variable for training.
#Default : If this variable is not provided, samples are extracted based on the Ground-Truth labels and the ROI. 
#weightedMapsForSamplingEachCategoryVal = ["./validation/weightMapsForeground.cfg", "./validation/weightMapsBackground.cfg"]

#+++++Full-Inference on validation cases+++++
#[Optional] How often (epochs) to perform full inference. It is time consuming... Default: 1
numberOfEpochsBetweenFullInferenceOnValImages = 5

#[Optionals] Specify whether to save the segmentation and probability maps for each class. Default: True to all
saveSegmentationVal = True
saveProbMapsForEachClassVal = [True, True]
#, False, False, False]

#[Required if requested to save results] The path to a file, which should list names for each validation case, to name the results after.
namesForPredictionsPerCaseVal = "./validation/validationNamesOfPredictions.cfg"

#--Feature Maps--
#Feature maps can also be saved, but section is omitted here. See testing configuration.

#==========Generic=============
#[Optional] Pad images to fully convolve. Default: True
padInputImagesBool = True

-----------------------------------------testconfig.cfg--------------------------------------------------

#Default values are set internally, if the corresponding parameter is not found in the configuration file.

#[Optional but highly suggested] The name will be used for naming folders to save the results in.
#Default: "testSession"
sessionName = "testSessionDeepMedic"

#[Required] The main folder that the output will be placed.
folderForOutput = "../../../output/"

#[Optional] The path to the saved CNN-model to use for testing. Optional in the case the the model is specified from command line with the -model option. In this case, this entry file of the config file will be disregarded, and the one from the command line will be used.
cnnModelFilePath = "../../../output/placeholder"

#+++++++++++ Input +++++++++++

#[Required] A list that should contain as many entries as the channels of the input image (eg multi-modal MRI). The entries should be paths to files. Those files should be listing the paths to the corresponding channels for each test-case. (see example files).
channels = ["./testChannels_Flair.cfg", "./testChannels_DWI.cfg","./testChannels_T2.cfg","./testChannels_T1.cfg"]

#[Required] The path to a file, which should list names to give to the results for each testing case. (see example file).
namesForPredictionsPerCase = "./testNamesOfPredictions.cfg"

#[Optional] The path to a file, which should list paths to the Region-Of-Interest masks for each testing case.
#If ROI masks are provided, inference will only be performed in within it (faster). If not specified, inference will be performed in whole volume.
roiMasks = "./testRoiMasks.cfg"

#[Optional] The path to a file which should list paths to the Ground Truth labels of each testing case. If provided, DSC metrics will be reported. Otherwise comment out this entry.
gtLabels = "./testGtLabels.cfg"

#+++++++++++Predictions+++++++++++
#[Optional] Specify whether to save segmentation map. Default: True
saveSegmentation = True
#[Optional] Specify a list with as many entries as the task's classes. True/False to save/not the probability map for the corresponding class. Default: [True,True...for all classes]
saveProbMapsForEachClass = [True, True]
#, False, False, False]

"""
#+++++++++++Feature Maps+++++++++++
#[Optionals] Specify whether to save the feature maps in separate files and/or all together in a 4D image. Default: False for both cases.
saveIndividualFms = True
saveAllFmsIn4DimImage = False

#[Optionals] A model may have too many feature maps, and some may not be needed. For this, we allow specifying which FMs to save. 
#Specify for each type of pathway (normal/subsampled/FC), a list with as many sublists as the layers of the pathway.
#Each sublist (one for each layer), should have 2 numbers. These are the minimum (inclusive) and maximum (exclusive) indices of the Feature Maps that we wish to save from the layer.
#The preset example saves the Feature Maps from index 0 (first FM) to 150 of the last hidden FC layer, before the classification layer.
#Default: [] for all.
minMaxIndicesOfFmsToSaveFromEachLayerOfNormalPathway = []
minMaxIndicesOfFmsToSaveFromEachLayerOfSubsampledPathway = [[],[],[],[],[],[],[],[]]
minMaxIndicesOfFmsToSaveFromEachLayerOfFullyConnectedPathway = [[],[0,150],[]]
"""

#==========Generic=============
#[Optional] Pad images to fully convolve. Default: True
padInputImagesBool = True

------------------------------------------------------------------------------------------------------------

I train this model with by 5-fold cross-validation on four modality (Flair, DWI, T1 and T2). I also normalized data to zero mean and unit variance. By online evaluation (test and train) average Dice for TrainingData=0.95, TestingData=0.52 was obtained. What is the reason for this problem? What do manipulate these settings?
Thank you very much!

**Comment by Kamnitsask** [comment]
Hello Zeinab, sorry for the late reply. Way too many deadlines in a PhD's life.

This is a standard case of overfitting. ISLES 15 training data is actually not much, so it's not a surprise at all that there is overfit of training (high training DSC) and relatively much lower testing DSC.

Many things can be tried to improve overfitting. For example, you could make a network with less filters at each layer, regularization, or employ more augmentation. It's not specific to this model nor this database.

I will close this issue, as this issue tracker is for technicalities of this codebase rather than discussing ML stuff like overfitting. More details on your other issue/question.

**Comment by ZeinabSalkhorde** [comment]
I really appreciate your attention and help. 
Regards
