### ISSUE TITLE
How do you do the normalization?

### ISSUE THREAD

**Issue by xyzacademic** [Kamnitsask/deepmedic#143]
Hello, Kamnitsask.
Could you tell me how did you do the normalization in pre-processing?
Computing mean and std per 2D scan, computing mean and std per patient's 3D image set or computing mean and std of whole dataset? Suppose the datasets' shape is (16, 120, 130, 140) (Patients, X, Y, Z). XY is the axial view. What is the normalization method?

I am very appreciate your help.

**Comment by samieti02** [comment]
Hello Sir,

here you have some good stuff about the normalization
#56 #72
