### ISSUE TITLE
Preprocessing: Registration

### ISSUE THREAD

**Issue by satrajitgithub** [Kamnitsask/deepmedic#147]
Hi @Kamnitsask ,

In the preprocessing, when you mention in the paper that "All images were resampled to an isotropic 1 mm 3 resolution, with dimensions 193 × 229 × 193 and affinely registered ( Studholme et al., 1999 ) to MNI space using the atlas by Grabner et al. (2006)", do you refer to the ICBM atlases on http://www.bic.mni.mcgill.ca/ServicesAtlases/ICBM152NLin2009 ?

**Comment by Kamnitsask** [comment]
Hello:

http://nist.mni.mcgill.ca/?p=858

**Comment by satrajitgithub** [comment]
Thank you so much!
