### ISSUE TITLE
Converting deepmedic to 16-bit

### ISSUE THREAD

**Issue by Geeks-Sid** [Kamnitsask/deepmedic#152]
Hi, Is there a way to convert the entire backbone of DeepMedic to use a FloatingPoint-16 to run?

Also, There are issues with saving images since 16bit images cannot be saved, so maybe during saving they could be converted to FloatingPoint-32.

**Comment by Kamnitsask** [comment]
Hi,

I think some functions/operators of TF were not supporting fl16 some time ago. I do not know where status is nowadays.

You could 'grep -r "float32" ./deepmedic/*' , replace it, try to run, and see what happens. Probably some more changes will be needed, but should not be too hard. But it may lead nowhere if some tf operator doesnt support fl16, no idea.

Kind regards,
Kostas
