### ISSUE TITLE
Efficient of Multi-scale?

### ISSUE THREAD

**Issue by John1231983** [Kamnitsask/deepmedic#153]
Dear Kamnitsask,

For multiple scale scheme, you used both original resolution and down-sample resolution to improve segmentation. I have a question related it

Let's assume input resolution is 1x1x1 mm. If we down-sample it 2x times, then the resampled image has resolution 2x2x2 mm. In your architecture, both resolutions are used. The label to compute the loss still used original resolution 1x1x1 mm. My question is that do you think your strategy will work well when input size is 2x2x2 mm, instead of 1x1x1 in the testing phase. I meant that given an image 2x2x2 mm, does your network still provide a good result? Because 2x2x2 mm is already trained using your strategy.

Thanks in advance

**Comment by Kamnitsask** [comment]
Hi John,

The network "looks" at the input via different scales (resolutions) "simultaneously".

By default, it looks at the "normal" resolution (whatever the input is) AND the downsampled (x2 by default) (AND downsampled by x3 in the current version of the code, AND any more scales if you specify more).

If the original resolution of the input is 1x1x1, this means the networks "looks" at it at the same time both as a 1x1x1, and as a 2x2x2 and as a 3x3x3.

If at test time you input an image with spacing 2x2x2, then it will be "looked at" as a 2x2x2 AND as a 4x4x4 (AND as a 6x6x6 in current default).

Your input can be of any spacing. What you need to ensure is that TRAIN and TEST images are of the same resolution. If you train with 1x1x1 spacing and test with 2x2x2 it wont work. You can train with 2x2x2 and test with 2x2x2. Or upsample the (2x2x2) to (1x1x1) and train & test with them.

I hope this clarifies things.

K
