### ISSUE TITLE
Question about training data

### ISSUE THREAD

**Issue by ZhongHai2018** [Kamnitsask/deepmedic#156]
hi,sir
After reading the code, I have a question.`~~~~~~~~~~~~~~~~~~~~INPUT~~~~~~~~~~~~~~~~
Number of cases to perform inference on = 2
Paths to the channels of each case = [['D:\\me\\graduationdesign\\DeepMedic\\deepmedic\\examples\\dataForExamples\\brats2015TrainingData\\test\\brats_2013_pat0001_1\\Flair_subtrMeanDivStd.nii.gz', 'D:\\me\\graduationdesign\\DeepMedic\\deepmedic\\examples\\dataForExamples\\brats2015TrainingData\\test\\brats_2013_pat0001_1\\T1c_subtrMeanDivStd.nii.gz'], ['D:\\me\\graduationdesign\\DeepMedic\\deepmedic\\examples\\dataForExamples\\brats2015TrainingData\\test\\brats_2013_pat0002_1\\Flair_subtrMeanDivStd.nii.gz', 'D:\\me\\graduationdesign\\DeepMedic\\deepmedic\\examples\\dataForExamples\\brats2015TrainingData\\test\\brats_2013_pat0002_1\\T1c_subtrMeanDivStd.nii.gz']]`
when we input image, we load Flair_subtrMeanDivStd.nii.gz and T1c_subtrMeanDivStd.nii.gz as the input.I want to know if the network has combine the two files into one before training.

**Comment by Kamnitsask** [comment]
Sorry for the late reply.

I am not sure I understand what you mean with "combine the two files" before training.

I guess you mean how the different channels are combined.

They are used as different channels at the input, similar to how RGB are considered different channels for CNN on natural images. Please see main paper publication or related literature on CNNs for details about the model and how CNNs work.

If I have not understood the issue correctly, please clarify and I will reopen if needed. For now I will close this.
