### ISSUE TITLE
Number of trainable parameters

### ISSUE THREAD

**Issue by chihyanghsu0805** [Kamnitsask/deepmedic#158]
Dear Kamnitsas,

Great Work!
I do have one very simple question.
How many trainable parameters are in the default model?
Thanks for your time.

**Comment by Kamnitsask** [comment]
Hello,

I will not answer this as the "default model" changes over time, so the answer will get deprecated.

Instead, calculating the number of parameters is extremely simple. Guides for this can be found in many places online.

In convolutional kernels of a layer = number_of_FMs_in_previous_layer * num_FMs_in_THAT_layer * kernel_w * kernel_h * kernel_d

Add the biases (one per fm in layer), the trainable params for other parts of the layer (BN, activation etc), and you have it.

(Spoiler: Original DM as described in Media 2017 publication had approximately 662,000 params)
