### ISSUE TITLE
Can DeepMedic run on multiple GPUs?

### ISSUE THREAD

**Issue by satrajitgithub** [Kamnitsask/deepmedic#161]
Hi Kostas,

Is there a way to run DeepMedic on multiple GPUs to speed up the process?
I am running it on a cluster with  3 GPUs but it seems I can only choose 1 GPU at a time (-dev cuda0 or -dev cuda1 etc.). I am testing results by changing various parameters of the architecture so for every change I make if I get the results in a shorter time, it will be great.

Thanks

**Comment by mark-joe** [comment]
But you can run your different experiments in parallel.

**Comment by Kamnitsask** [comment]
Hello, thank you for your interest in our work, and very sorry for the late reply, my schedule is overwhelmed (thesis writing >.<).

The current implementation cannot use multiple GPUs. Supporting this functionality is not of high priority for me.

As the above user mentioned, it's common practice to run multiple experiments in parallel to utilize multiple GPUs. In most research environments I think this is common practice. 

Of course I understand it would be nice to speed up a single experiment, but multi-gpu would take non-trivial modifications I think, and I have to prioritize other aspects for extension and maintenance of DM.

Thank you!
