### ISSUE TITLE
How about brain CT images

### ISSUE THREAD

**Issue by bsc0001** [Kamnitsask/deepmedic#162]
Hello,

I'm wondering if this could be used to train a set of data, but being CT images, instead of MRI. And if so, how would it affect configuration?

Thank you in advance

**Comment by Kamnitsask** [comment]
Hello,

Yes, it can be used for CT, we have used it very well for segmentation of various structures in CT (cardiac, brain, multiorgan, etc) without changes to the model.

Only take care of the preprocessing. Intensity windowing, change intensity ranges to something more appropriate for the CNN (eg scale them to (-5,+5) or (-1,+1) range, mask out parts that dont matter (eg skull).). Best preprocessing is dependent on the task. So you ll need to experiment with this. Difficult to give a rule of thumb, it's really task dependent.
