### ISSUE TITLE
cnnModel folder not found

### ISSUE THREAD

**Issue by shubashri123** [Kamnitsask/deepmedic#168]

**Comment by shubashri123** [comment]
Hi kamnitsask
            I'm facing an issue in after training process. In my output folder i can't find  ./examples/output/cnnModels/tinyCnn.initial.DATE+TIME.model.ckpt.[data..., index]  and other three folders are created. Therefore I'm facing issue during training  please help me out.

**Comment by Kamnitsask** [comment]
The files should be there, just make sure that you are looking for the correct name of file (replace tinyCnn/initial/DATE+TIME/etc as needed).
