### ISSUE TITLE
Question on size of input data

### ISSUE THREAD

**Issue by josephwinston** [Kamnitsask/deepmedic#18]
The ```README.md``` notes that the software was used on data scans of about 200x200x200.  Do you have any rules of thumb on the relationship between input data size and GPU memory usage?

**Comment by Kamnitsask** [comment]
Hello,

The memory usage is defined by two things in my implementation:
-The size of the network (layers, number of fms etc)
-The batch size 
-The dimensions of the input segment (segmentsDimTrain/Val/Inference in modelConfig.cfg)

The input image is broken into segments of the specified size. So, the size of the actual image does not really influence the memory.

Rule of Thumb:
    When it comes to the input image's resolution, there is another important rule of thumb. Whether the CNN's receptive field is big enough. Eg, my "deepmedic" configuration has a receptive field of 17^3 voxels. The "low resolution" pathway also looks at 17^3 voxels, but in a downsampled by 3 times version of the image, thus in an area of 51^3. 
    Now, no matter the size of the image, when it's segmenting a voxel, this CNN is looking at a neighborhood of 17^3(51^3) voxels. If you believe this is too little for your problem, you need to make a bigger CNN (more layers), increase the low-resolution pathway's subsampling factor, or downsample the original image.

Hope this helps.
Kostas

**Comment by josephwinston** [comment]
I had completely missed the importance of the CNN's receptive field.  Thank you for pointing it out to me.

Your notes here plus the ```READEME.md``` give me an idea of how to adjust deepmedic to work on my data.  I'll let you know if anything comes of it.
