### ISSUE TITLE
Can I train if without the Flair dataset

### ISSUE THREAD

**Issue by sunle2009** [Kamnitsask/deepmedic#20]
Hi,
Thanks for your great work on Medicine deep learning.
I am trying to study your work to process brain MRI images. I only have the T1-enhanced MRI and the corresponding segmentation labels. 
Can I train without the Flair images please?

Thank you.

**Comment by Kamnitsask** [comment]
Hello there,

Yes, absolutely. You will just need to modify the config files accordingly. (modelConfig to say you provide only 1 modality, and trainconfig to point to only T1enhanced files).

Please read the readme, explore the config files a bit, and I believe you will understand how it's done easily.

Kostas
