### ISSUE TITLE
Can we apply this on sequence of 3D images?

### ISSUE THREAD

**Issue by devareddy** [Kamnitsask/deepmedic#25]
Hi Kamnitsask,

Thanks for the code and tinyCnn model is working well.
I am curious to know if, we can apply this for sequence of 3D images.
Your help is highly appreciated!

-Dev

**Comment by Kamnitsask** [comment]
Hello Dev,

I guess you mean 3D volumes + time?

The current code has in quite some functions the assumption of 3 dimensions. So, at its current state, it cannot.

The extension to 4D should need small changes in the code, but they will be needed in a lot of places. I am not sure how easy it is for someone else other than me to follow the control-flow of the process and find all these places that need change. Probably would be tricky.

Currently, it's not in my plans to support this functionality. You could have a brief look into the code, starting point at ./deepMedicRun and going deeper. If you think it's readable and could be done, email me to speak further. If you think it'd take you a while, then I d suggest you look at other alternatives.

Kind regards,
Kostas

**Comment by devareddy** [comment]
Hi Kostas,

Thanks for the reply!.
Sequence in this context i referring to multiple images sent a time not
just one.
As you know usually CT/MRI scans will have sequence images for a patient.
I am curious to know if i could submit sequence of images ~200 at time and
classify the images.
As in examples i noticed you are submitting only one image patch of patient
for training and classification.
Hope i explained well, other wise i can share more details.

Thanks in advance,
Deva

**Comment by Kamnitsask** [comment]
Hello Deva,

I am sorry, but this is still unclear to me.

You say the CT/MRI usually have "sequence images" for a patient. Do you mean that they are 3D volumes, ie have many slices? If so, the software is made for processing exactly this type of data. For the segmentation of each voxel it processes 3D information, taking into account not only voxels from one slice, but from multiple.

If you are talking about 4D volumes, eg CT/MRI with the 4th dimension being time (eg for cardiac imaging, where to analyse the whole cycle of the beating heart), then quite some changes in the code would be needed.

It is not clear to me what you mean with "submit sequence of images ~200 at time and
classify the images.". I would suggest you explain in more detail/clearer what you mean. Bear in mind that the software is a segmenter. It does not "classify images". It "classifies voxels" instead, indirectly by classifying the contents of the patch surrounding each voxel. Hope this helps with any confusion.

Kind regards,
Kostas
