### ISSUE TITLE
It goes wrong when I use validation data

### ISSUE THREAD

**Issue by viridyu** [Kamnitsask/deepmedic#30]
Hello,

I split the whole BRATS2015 data into training and validation for deepmedic model. However, when I set:

performValidationOnSamplesThroughoutTraining = Ture
performFullInferenceOnValidationImagesEveryFewEpochs = Ture, 

it always goes wrong as:

No such file: '/home/by354/mywork/testcode/Segmentation_myimplement/deepmedic/examples/configFiles/dataForExamples/BRATS2015/validation/VSD.Brain_3more.XX.O.OT.42493/VSD.Brain_3more.XX.O.OT.42493_mask.nii'

Actually, I have the right file in the directory. 

Any ideas what could be happening?

**Comment by Kamnitsask** [comment]
Hello viridyu,

I am sorry for this inconvenience. I don't think there has been a problem with the path-parsing reported before. Could you please email me your logs from the training session (at konstantinos.kamnitsas12@imperial.ac.uk)? Perhaps I ll be able to understand what's wrong from there. In the meantime, please ensure that this abolute path is accurate.

Kind regards,
Kostas

**Comment by roelant001** [comment]
I've made the mistake of using relative paths and using too few ../../../../ 's for the validation config file a couple of times,due to the extra sub-folder compared to the training config file. 
Did you check your data is indeed in examples/**configFiles**/dataForExamples and not in examples/dataForExamples ?

**Comment by viridyu** [comment]
Thank you, @roelant001 and @Kamnitsask . I think I copy  the wrong relative paths with too few ../. Thank you again for your help.
