### ISSUE TITLE
Using gpu device 0: GeForce GTX 960 (CNMeM is disabled, cuDNN 5005)

### ISSUE THREAD

**Issue by mjiansun** [Kamnitsask/deepmedic#34]
CPU is ok.When i use gpu(cuda7.5 cudnnv5),i have this question:
Using gpu device 0: GeForce GTX 960 (CNMeM is disabled, cuDNN 5005)

**Comment by anewlearner** [comment]
Nothing to do with this project. It is related to the theano configuration.
[https://github.com/Theano/Theano/issues/4677](url)

**Comment by Kamnitsask** [comment]
Hello mjiansun,

This message is a standard message from Theano, which you get at the beginning if you successfully configure it to run on a GPU.

The number after "Using gpu device", "0" in your case, says which GPU is used (eg cluster machines can have multiple gpus).

CNMem is disabled, can be enabled via theano configuration if needed. Look in theano documentation. 

Last part tells you which CuDnn version is used.

It's not an error message. Rather a confirmation that you are indeed using a gpu.

ps: Thanks a lot newlearner for the help, appreciated.

K

**Comment by JavierCoronel** [comment]
Hi, i've been usign the GPU with as usual with -dev gpu. Is it possible to use more than one GPU using -dev +somethingelse ?
Thanks in advance

**Comment by Kamnitsask** [comment]
Hi,

You can specify which gpu to use by giving its number. Eg with -dev gpu3 you ll use the gpu-number-3 if you have a cluster with four.

But, distributing the processing (eg training batches) of a single network to multiple gpus is not supported. Currently I m not planning to look into this functionality.

K
