### ISSUE TITLE
ValueError: Input dimension mis-match. (input[0].shape[2] = 1, input[1].shape[2] = 2)

### ISSUE THREAD

**Issue by tuttoweb** [Kamnitsask/deepmedic#37]
Hello,
I am trying to train the deepmedicOriginal model using ISLES data (preprocessed using the methodology you suggested). I made several trials which have always worked. Today, I was trying just one modality and I am getting this error that I cannot debug by myself:

**************************************************************************************************
************* Starting new Subepoch: #0/20 *************
**************************************************************************************************
:=:=:=:=:=:=:=:=: Starting to extract Segments from the images for next Validation... :=:=:=:=:=:=:=:=:
Out of [1] subjects given for [Validation], it was specified to extract Segments from maximum [1] per subepoch.
Shuffled indices of subjects that were randomly chosen: [0]
SAMPLING: Starting iterations to extract Segments from each subject for next Validation...
SAMPLING: Going to load the images and extract segments from the subject #1/1
Loading subject with 1st channel at: /home/s1582461/idcom_imaging/data/deepmedic_isles_data/VFlair/19.nii.gz
DEBUG: Index of this case in the original user-defined list of subjects: 0
Images for subject loaded.
From subject #0, sampling that many segments of Category [Uniform] : 5000
Finished sampling segments of Category [Uniform]. Number sampled: 5000
TIMING: Extracting all the Segments for next Validation took time: 1.58(s)
:=:=:=:=:=:=:=:=: Finished extracting Segments from the images for next Validation. :=:=:=:=:=:=:=:=:
Loading Validation data for subepoch #0 on shared variable...
DEBUG: For Validation, loading to shared variable that many Segments: 5000
TIMING: Loading sharedVariables for Validation in epoch|subepoch=0|0 took time: 0.0(s)
PARALLEL: Before Validation in subepoch #0, the parallel job for extracting Segments for the next Training is submitted.
-V-V-V-V-V- Now Validating for this subepoch before commencing the training iterations... -V-V-V-V-V-
Validated on 0/104 of the batches for this subepoch...
Traceback (most recent call last):
  File "./deepMedicRun", line 102, in <module>
    deepMedicTrain.deepMedicTrainMain(absPathToTrainConf, absPathToCnnModelGivenInCmdLine, cnnInstanceLoaded, filenameAndPathWhereNewlyCreatedModelWasSaved)
  File "/remote/rds/groups/idcom_imaging/deepmedic/deepmedic/frontEndModules/deepMedicTrain.py", line 449, in deepMedicTrainMain
    do_training(*trainSessionParameters.getTupleForCnnTraining())
  File "/remote/rds/groups/idcom_imaging/deepmedic/deepmedic/trainValidateTestVisualiseParallel.py", line 1232, in do_training
    validationAccuracyMonitorForEpoch)
  File "/remote/rds/groups/idcom_imaging/deepmedic/deepmedic/trainValidateTestVisualiseParallel.py", line 930, in doTrainOrValidationOnBatchesAndReturnMeanAccuraciesOfSubepoch
    listWithMeanErrorAndRpRnTpTnForEachClassFromValidation = cnn3dInstance.cnnValidateModel(batch_i)
  File "/home/s1582461/idcom_imaging/myanaconda/mypython/lib/python2.7/site-packages/theano/compile/function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/s1582461/idcom_imaging/myanaconda/mypython/lib/python2.7/site-packages/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/s1582461/idcom_imaging/myanaconda/mypython/lib/python2.7/site-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
ValueError: Input dimension mis-match. (input[0].shape[2] = 1, input[1].shape[2] = 2)
Apply node that caused the error: Elemwise{add,no_inplace}(InplaceDimShuffle{0,4,1,2,3}.0, InplaceDimShuffle{x,x,0,x,x}.0)
Toposort index: 336
Inputs types: [TensorType(float32, 5D), TensorType(float32, (True, True, False, True, True))]
Inputs shapes: [(48, 17, 1, 17, 17), (1, 1, 2, 1, 1)]
Inputs strides: [(19652, 4, 19652, 1156, 68), (8, 8, 4, 4, 4)]
Inputs values: ['not shown', array([[[[[ 0.]],

         [[ 0.]]]]], dtype=float32)]
Outputs clients: [[Reshape{4}(Elemwise{add,no_inplace}.0, TensorConstant{[816   2  17  17]})]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

What could it be?

**Comment by tuttoweb** [comment]
I solved it.
The problem was that the original deepmedic network expects 2 inputs, whereas I wanted to train my network with just an input modality. Keeping this message will help other users that may encounter this issue

Thanks

**Comment by Kamnitsask** [comment]
Hello tuttoweb,

I m glad you found your problem. 

For future reference:
The "modelConfig.cfg" has an entry for specifying how many input channels the model will be getting. By default, this is set to two (numberOfInputChannels = 2), so that it's compatible with the preset example in the documentation. Building a model and then providing different number of input channels at train/test time will break the process.

I m sorry that these error messages are not very intuitive. Most of them come from Theano itself. I  ll try to make some more intuitive ones myself, but this is prioritized low for now.

Thanks a lot for your interest and feedback tuttoweb.

Kind regards
Kostas

**Comment by tuttoweb** [comment]
Thanks Kostas for your comment.
I know that these messages come from Theano and for me they are still very hard to debug it. 
My problem was I gave for granted the model deepMedicOriginal, without considering that I needed to adapt input and output for my case.

Thank you for your work
Best
vg

**Comment by saaltfiish** [comment]
Hi Kamnitsask and tuttoweb,
I have already changed "numberOfInputChannels" to 4 and accordingly added the other 2 modality config files. The logger shows reading these files successfully. But I'm still getting this error... How could it be? And How to solve it?
Thanks
