### ISSUE TITLE
Where is the 3D Dense CRF?

### ISSUE THREAD

**Issue by Kamnitsask** [Kamnitsask/deepmedic#38]
As I got some emails about this:

The implementation of the fully-connected 3D CRF used in our work is at:
https://github.com/Kamnitsask/dense3dCrf

You ll have to configure the meta-parameters for your problem though.

I did it with random search. ie a script that runs the crf again and again with random parameters, and logs its performance for its run. In the end, use the parameters that worked best on your validation set.

K

**Comment by qinhaifangpku** [comment]
Hi, Kamnitsask,

Thanks for your contributions!

I want to know how you do to search the parameters of CRF?

Could you please provide the script of search parameters?

**Comment by Kamnitsask** [comment]
Hi,

It's a "random search". i.e., run it multiple times with random parameters, and chose the best ones. I cannot provide a script for this, but should only take a couple of days to write one.
