### ISSUE TITLE
Unable to use GPU

### ISSUE THREAD

**Issue by starofgit** [Kamnitsask/deepmedic#40]
Hi,

My system has two K80 Nvidia GPUs, but I am unable to use GPUs(it shows that memory of the GPU has been utilized, but  GPU utilization is 0%, while CPU utilization is full. I have CentOS Linux release 7.2.1511 installed on my system with CUDA7.5, Theano0.8.0, CuDNN4 and CNMEM.

It gave the following message when I ran the code:
Using gpu device 1: Tesla K80 (CNMeM is enabled with initial size: 98.0% of memory, CuDNN 4007)
That means, it should use GPU properly

This is the command I gave to train the network:
python ./deepMedicRun -dev gpu1 -train ./examples/configFiles/deepMedic/train/trainConfig.cfg -model examples/output/cnnModels/deepMedic.initial.2017-02-09.15.26.35.367588.save

Could you please tell me the solution? Could you please provide a docker image for Deepmedic?

Thanks

**Comment by Kamnitsask** [comment]
Hello starofgit,

thanks for your interest and your feedback.

The message you receive indeed should mean that everything is fine and GPU is used. 

The gpu usage can be low if you changed something in the configuration that makes the process very light on the GPU, and the training on the batches is done very fast, while CPU stays busy extracting patches for the next batch. For instance, this can happen if you deliberately used a very small network or with very few filters.

How are your training times? Is the model getting trained or not?

Would you mind sending me the log files from your training to konstantinos.kamnitsas12@ic.ac.uk? They will help me spot a problem if there is one.

I have not scheduled of providing docker image, sorry.

Kind regards,
Kostas

**Comment by Kamnitsask** [comment]
Closing for now as there was no update on this issue.
