### ISSUE TITLE
Request: pre-trained model?

### ISSUE THREAD

**Issue by shoshber** [Kamnitsask/deepmedic#46]
I saw in issue #42 that you were considering providing the pre-trained model. +1 to that! If there's anything I can do to make that happen, let me know.

**Comment by Kamnitsask** [comment]
Hello,

I am thinking of it. There are quite some technical problems (mostly, need to adress incompatibilities of different versions of deepmedic, theano, cuda etc). Slowly getting there.

An interesting question here:
What kind of pretrained model would you be interested in and for what purpose? Eg a BRATS-trained model? What would you use it for? Compare against it on BRATS? Fine-tune it on other databases? 

Any comments about potential usage would help me think of what to release that would prove actually useful in practice for users.

K
