### ISSUE TITLE
Same scores/accuracy for class-0 and class-1 in binary problems

### ISSUE THREAD

**Issue by JavierCoronel** [Kamnitsask/deepmedic#48]
Hi,

I trained a CNN for the binary problem of aortic segmentation, so I changed the input chanels and the number of classes. But when I chek the logs of the training and validation sesions, I get the same scores for both classes (Class-0: mean accuracy: 0.9614; Class-1: mean accuracy: 0.9614, and so on) Am I mixing data or something else? 
Also, when plotting the training process, I only get the Class-0 label results, there is no other legend or other color for Class-1. Is this also because of the same scores during training? 

However, when testing the CNN, the results are very impressive and it seems to work on aortic segmentation

Javier

**Comment by Kamnitsask** [comment]
Hello,

This is actually normal. In Ground Truth, label == 0 is supposed to be for the background.
Accuracy on Class-0 would mean reporting accuracy for background:
- eg, accuracy-0 = true_pos_background / number_of_background_voxels_in_groundTruth
*Instead*, something that I find more useful, and what we actually report now for Class-0 is to report the inverse. The accuracy for the "foreground" (= all classes except the 0 merged):
- eg, accuracy-0 = true_pos_foreground / number_of_foregorund_voxels_in_groundTruth

In the case of a *binary* problem, this is actually the same as the accuracy for class-1. (foreground is the merge of all non-background-0 classes, which in this case is just class-1). 
But this makes a difference in multi-class problems. Eg in multiclass segmentation of the different cardiac structures (Left/right ventricles, atriums etc), class-0 accuracy would correspond to the accuracy of segmenting the whole foreground, ie the WHOLE heart.

Both the accuracy for class-0 in the logs and the accuracy in the plots follow this principle. Sorry if it is not clear. I have tried to document this in various places in the logs and in the -h of the plotting script.

Thanks a lot for the feedback. I will try to rethink about it and how to make it clearer.

ps: Super nice to know it works for the aorta. I am thinking of making a documentation about cases / tasks / problems where me and users have found it working well / bad. Feel free to send me an email with a pointer to your work, that I could refer to when when I make such a collection (konstantinos.kamnitsas12@imperial.ac.uk).

Kind regards,
Kostas

**Comment by JavierCoronel** [comment]
Thanks, now I understand. So, for multiclass segmentation, class-0 will be always segmenting foreground. 

Does that mean when checking the scores/accuracy in tinyCnn example ,and in general for multiclass tasks, class-0 is for the foreground (taking into account the whole lesion), and class-1...4 are for the individual types of lesion?

I'll try adding more classes to my model and let you know the results.

Javier

**Comment by Kamnitsask** [comment]
Yeap, that's exactly what class-0 would report in the case of multiclass tumor segmentation. The whole tumor's DSC.

K
