### ISSUE TITLE
How to change gpu device?

### ISSUE THREAD

**Issue by lly2111101** [Kamnitsask/deepmedic#51]
Thanks for your great work. I come across some problems on gpu memory even though there is enough memory left. How can I specially the gpu device? (I tried -dev gpu3/2/1 but it didn't work.) Thanks.

**Comment by lly2111101** [comment]
For example, when I run command line "./deepMedicRun -dev gpu2 -newModel ./examples/configFiles/deepMedic/model/modelConfig.cfg -train ./examples/configFiles/deepMedic/train/trainConfig.cfg", it reported an error : 
"Couldn't import dot_parser, loading of dot files will not be possible.
ERROR (theano.sandbox.cuda): ERROR: Not using GPU. Initialisation of device 2 failed:
Bad device number 2. Only 1 devices available.
Traceback (most recent call last):
  File "./deepMedicRun", line 90, in <module>
    from deepmedic.frontEndModules import deepMedicNewModel
  File "/raid/luyanliu/deepmedic/deepmedic/frontEndModules/deepMedicNewModel.py", line 12, in <module>
    from deepmedic.cnn3d import Cnn3d
  File "/raid/luyanliu/deepmedic/deepmedic/cnn3d.py", line 11, in <module>
    import theano
  File "/usr/local/lib/python2.7/dist-packages/theano/__init__.py", line 111, in <module>
    import theano.sandbox.cuda
  File "/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/__init__.py", line 713, in <module>
    use(device=config.device, force=config.force_device, test_driver=False)
  File "/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/__init__.py", line 556, in use
    gpu_init(device, config.lib.cnmem)
ValueError: ('Bad device number 2. Only 1 devices available.', 'You asked to force this device and it failed. No fallback to the cpu or other gpu device.')".
Do I need to change some configurations in Theano?

**Comment by Kamnitsask** [comment]
This seems to have to do with your cuda not seeing more than 1 available GPUs. Not with this software I believe.

Check if nvidia-smi shows more than 1. Check if anything in your own scripts is limiting the CUDA_VISIBLE_DEVICES. Finally, try to run another theano script, from some tiny tutorial, and check if that can run on another gpu successfully, or you get the same error.

Hope the above helps.
Kostas

**Comment by lly2111101** [comment]
Hi Kamnitsask,

I didn't change a lot of your script because I just want to reproduce your
method. I run the tiny tutorial with command "-dev gpu2" and it failed
either. There is 4 GPUs available in our server. It is the output of
nvidia-sim:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.57                 Driver Version: 367.57
   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr.
ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute
M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 0000:05:00.0      On |
 N/A |
| 52%   82C    P2   135W / 250W |   4138MiB / 12203MiB |      2%
 Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  Off  | 0000:06:00.0     Off |
 N/A |
| 22%   52C    P8    17W / 250W |      3MiB / 12206MiB |      0%
 Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX TIT...  Off  | 0000:09:00.0     Off |
 N/A |
| 43%   83C    P2   157W / 250W |   7237MiB / 12206MiB |    100%
 Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX TIT...  Off  | 0000:0A:00.0     Off |
 N/A |
| 36%   79C    P2   199W / 250W |  11693MiB / 12206MiB |    100%
 Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU
Memory |
|  GPU       PID  Type  Process name                               Usage
   |
|=============================================================================|
|    0      1963    G   /usr/bin/X
 44MiB |
|    0      5672    C   caffe
4090MiB |
|    2     17173    C   caffe
7232MiB |
|    3     10330    C   python
11690MiB |
+-----------------------------------------------------------------------------+
The output of failed tiny one (./deepMedicRun -dev gpu2 -newModel
./examples/configFiles/tinyCnn/model/modelConfig.cfg) is still the same,
which is "Couldn't import dot_parser, loading of dot files will not be
possible.
ERROR (theano.sandbox.cuda): ERROR: Not using GPU. Initialisation of device
2 failed:
Bad device number 2. Only 1 devices available.
Traceback (most recent call last):
  File "./deepMedicRun", line 90, in <module>
    from deepmedic.frontEndModules import deepMedicNewModel
  File
"/raid/luyanliu/deepmedic/deepmedic/frontEndModules/deepMedicNewModel.py",
line 12, in <module>
    from deepmedic.cnn3d import Cnn3d
  File "/raid/luyanliu/deepmedic/deepmedic/cnn3d.py", line 11, in <module>
    import theano
  File "/usr/local/lib/python2.7/dist-packages/theano/__init__.py", line
111, in <module>
    import theano.sandbox.cuda
  File
"/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/__init__.py",
line 713, in <module>
    use(device=config.device, force=config.force_device, test_driver=False)
  File
"/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/__init__.py",
line 556, in use
    gpu_init(device, config.lib.cnmem)
ValueError: ('Bad device number 2. Only 1 devices available.', 'You asked
to force this device and it failed. No fallback to the cpu or other gpu
device.')"

Is the default gpu device setting to 0 in this script? Does this mean that
the software always using gpu 0 to process or it will search an available
one to use?
Thanks a lot for you replying.

I just run the common "./deepMedicRun -dev gpu -newModel
./examples/configFiles/deepMedic/model/modelConfig.cfg
                         -train
./examples/configFiles/deepMedic/train/trainConfig.cfg"
several seconds ago again. It works at least by now. But I don't know
whether it will be interrupted again because of gpu memory?

Best,
Luyan Liu

**Comment by Kamnitsask** [comment]
I believe this is not a deepmedic issue but something that has to do with your cuda configuration or cluster config. Check/try the below:

Is there a chance that somehow you guys (or the admin of the cluster) configured the cluster to allow only 1 process to run on each GPU, and when one is occupied, that busy GPU to be considered "invisible"/unavailable for the rest of the processes that want to start?

(I believe this can actually be done, don't ask me how.)
1) Try using gpu1/2/3 when not only 1 gpu is free and check if the output still states "only 1 devices available."

2) Try to run a small Theano tutorial (http://deeplearning.net/software/theano/tutorial/using_gpu.html) and check if that works when specifying GPU. Cause I am pretty sure the problem is not deepmedic but something else.

3) The default configuration should never need more memory than the 12GBs of a titan. The only reason it may "out of memory" crash is if someone else also starting running stuff on that GPU. To not allow anyone else to run stuff on the GPU you use, an easy way is to simply tell theano to reserve the whole GPU memory for itself when it starts.

To do (3), edit ./deepMedicRun, look for the line with the THEANO_FLAGS, and at the end of the string, and edit it by adding: "....force_device=True,lib.cnmem=1".

(I won't explain cnmem further here, it's a Theano thing. Find details at http://deeplearning.net/software/theano/library/config.html)

Hope the above help,
Kostas

**Comment by lly2111101** [comment]
Thanks a lot for your answers. I absolutely agree with you and I also think
that it is something about the configuration of THEANO and there are so
many tasks running on GPU server. I will find another way to solve this
problem. Thanks again for your patient reply.


Best,
Luyan Liu

**Comment by Kamnitsask** [comment]
hope the info helps. Let us know when you solve it and how. It could help other users that run into the same issue.

K

**Comment by lly2111101** [comment]
Your information really helps a lot. I redo the experiment again with
"export  CUDA_VISIBLE_DEVICES=2" and "lib.cnmem=1". Thanks a lot for
sharing your great work with us and your patient reply.


Best,
Luyan
