### ISSUE TITLE
A very basic question

### ISSUE THREAD

**Issue by teamsar** [Kamnitsask/deepmedic#53]
Hi sorry, I wanna ask a very basic question. I'm newbie in python and want to learn lesion segmentation using CNN, when I installed setup.py, it returned errors like this:

  File "build\bdist.win-amd64\egg\deepmedic\accuracyMonitor.py", line 122
    meanDiceOfSubep ] = self.listPerSubepPerClassMeanAccSensSpecDsc[currSubep][class_i] if class_i <> 0 else \
                                                                                                    ^
SyntaxError: invalid syntax

  File "build\bdist.win-amd64\egg\deepmedic\cnn3d.py", line 164
    if pathway.pType() <> pt.FC :
                        ^
SyntaxError: invalid syntax

  File "build\bdist.win-amd64\egg\deepmedic\cnnHelpers.py", line 59
    if logger <> None :
               ^
SyntaxError: invalid syntax

  File "build\bdist.win-amd64\egg\deepmedic\cnnLayerTypes.py", line 616
    print "ERROR: For LowRankConvLayer, the ._W is not used! Use ._WperSubconv instead and treat carefully!! Exiting!"; exit(1)
                                                                                                                     ^
SyntaxError: invalid syntax

  File "build\bdist.win-amd64\egg\deepmedic\cnnTransferParameters.py", line 40
    depthLayerTarget = layerTarget_i + 1 if typePathTarget <> pt.FC else layerTarget_i + 1 + len( cnnTarget.pathways[0].getLayers() ) # +1 cause indexes. index 0 is depth 1.
                                                            ^
SyntaxError: invalid syntax

  File "build\bdist.win-amd64\egg\deepmedic\frontEndModules\deepMedicNewModel.py", line 88
    print "Given Model-Configuration File: ", modelConfigFilepath
                                           ^
SyntaxError: Missing parentheses in call to 'print'

  File "build\bdist.win-amd64\egg\deepmedic\frontEndModules\deepMedicTest.py", line 61
    print "Checking if configuration is correct in relation to the loaded model (correct number of input channels, number of classes, etc) ..."
                                                                                                                                              ^
SyntaxError: invalid syntax

  File "build\bdist.win-amd64\egg\deepmedic\frontEndModules\deepMedicTrain.py", line 127
    print "Checking if configuration is correct in relation to the loaded model (correct number of input channels, number of classes, etc) ..."
                                                                                                                                              ^
SyntaxError: invalid syntax

Anyone know how to fix this. I assume, this project is 100% running smoothly.

**Comment by Kamnitsask** [comment]
Hello,

First of all, definitely do not assume this is 100% running smoothly :) I am doing my best but it's far from it.

My guess is that you are using python 3? (just write "python" in a terminal, and check the version that it ll show in the interactive terminal). The project is following python 2 syntax unfortunately.

You can try installing python 2.7 and try the setup.py again?

Kind regards,
Kostas

**Comment by teamsar** [comment]
Hi,

Thanks.. I changed the environment from 2.7 to 3.5 since I work on a project that runs on python 3.5. So, I need to switch it back to 2.7 and it works. Thanks
