### ISSUE TITLE
python3 incompatibility with pp (parallel python)

### ISSUE THREAD

**Issue by Kamnitsask** [Kamnitsask/deepmedic#58]
Python 3 compatibility changes on branch python3compat. To be merged to master soon.

However there is problem with the compatibility of pp (parallel-python module, download from http://www.parallelpython.com/content/view/18/32/). Stable version 1.6.5 is not python3 compatible and can be taken via pip. Version 1.6.4.4 is beta, python3 compatible, but at the moment is not found via pip.

To work for python3, currently, download 1.6.4.4 from above link, and install manually by running "pip install ." in the downloaded folder.

I should check for when a stable version is released. Or remove pp and use python's parallel processing package instead.

**Comment by pretsnor** [comment]
As of 31 oct 2018, this is still a problem. 

Thanks for the workaround, Kamnitsask.

**Comment by Jean-Rassaire** [comment]
Hi Kamnitask.
I tried to install pp  and i got the following error:

(MachineLearning) C:\Users\Jean-Rassaire>conda install -c geneko pp
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - grpcio
  - pp
Use "conda info <package>" to see the dependencies for each package.

**Comment by lukaszimmermann** [comment]
Are there current updates on this issue? We would like to use DeepMedic for our work and we depend on Python 3.

@Kamnitsask Are there current plans from your side? I don't think that pp is going to be updated for Python 3 anytime soon. Would it be feasible to switch to the `multiprocessing` module? Thanks a lot.

**Comment by Kamnitsask** [comment]
Yes, there are plans to change this. The only issue is time, and I ll try to come back to this in a month.

Since the workaround I ve given up top is super easy (takes 1 min), so this change was not highest priority. Now that python2 is discontinued, priorities change of course.

K

**Comment by lukaszimmermann** [comment]
Thanks a lot for the update. The workaround works for me.

If you can point me to the relevant parts in the code, I can perhaps help and start a corresponding PR.

**Comment by multithink** [comment]
Hi there 

I am trying to use Deep-medic in google colab. I would appreciate if you help me for the downloading of parallel python in colab. I am getting this error;

!pip install Parallel Python 

Collecting Parallel
 Using cached https://files.pythonhosted.org/packages/31/5b/66966fb4d103191b7cbc92730db6a335986fbdb3d9f55cbb54b7ba87e9d4/parallel-0.2.5.tar.gz
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-r26qg7_h/Parallel/

**Comment by Kamnitsask** [comment]
Hi Lukas,
(sorry for the late reply. I was overwhelmed with teaching-stuff.)

I will look into the replacement of pp by multiprocessing immediately. I had actually done this in the past but it was never pushed. And I want to check how it interacts with logging.

The related lines are in ./deepmedic/routines/training.py:
Line 183: the instantiation of the "job_server"
Line 306, 373, 379, the 3 job submissions to job_server
L 297 & 364, getting the results back from the submitted jobs.

I will likely work on this today/tomorrow already, and push something on a separate branch for debugging. If you are experienced with multiprocessing, I can update you in case you would like to have a quick look.

**Comment by Kamnitsask** [comment]
Hi multithink,

I am sorry, I have literally never touched colab. I am working on taking pp out, I will update this issue when it's done. (hopefully in a couple of days.)

**Comment by Kamnitsask** [comment]
Hello,

Commit  c5d6f67 replaces pp with:
from multiprocessing.pool import ThreadPool
threadPool = ThreadPool(processes=1)

Quick checks seem to be showing consistent behaviour.

It is on branch "multiprocessing". I will run some processes overnight, check how is the behaviour if exceptions are thrown from the parallel thread, and I will merge tomorrow-ish on master if everything looks ok.

K

**Comment by Kamnitsask** [comment]
This has been addressed in commit ad9917c , v0.7.1, on master as of 13 Feb 2019.

The pp multiprocessing library has been removed. It served it's purpose well till now but we move on.

Multiprocessing now is done via python's builtin module, multiprocessing.

This thus has no problems with python3, which is now the by default recommended library in the documentation.

Note on how multiprocessing is done now:
- During training, main thread spawns a thread as a sampler.
- The sampler can spawn multiple subprocesses, that each one loads data of a training/validation case, and extracts samples from it.
- Experiments on a single desktop and on a cluster suggest the process is faster (much faster in our cluster, where pp tended to become superslow when multiple users where overwhelming the CPUs. Seems Multiprocessing's processes are somehow handled better by the scheduler? Not sure).

Number of child sampling processes controlled in trainConfig.cfg, via variable:
num_processes_sampling = *some_integer*

Thank you all for the feedback!
Kostas
