### ISSUE TITLE
change numberTrainingSegmentsLoadedOnGpuPerSubep

### ISSUE THREAD

**Issue by viridyu** [Kamnitsask/deepmedic#59]
Hi,

When I change the numberTrainingSegmentsLoadedOnGpuPerSubep=10000, it always shows a error as,

A fatal error has occured during the function execution
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ppworker.py", line 97, in run
    self.pickle_proto)
SystemError: error return without exception set
Traceback (most recent call last):
  File "./deepMedicRun", line 119, in <module>
    deepMedicTrain.deepMedicTrainMain(absPathToTrainConf, absPathToCnnModelGivenInCmdLine, cnnInstanceLoaded, filenameAndPathWhereNewlyCreatedModelWasSaved, args.reset_optimizer)
  File "/home/by354/mywork/testcode/Segmentation_myimplement/deepmedic-freezeLayers/deepmedic/frontEndModules/deepMedicTrain.py", line 496, in deepMedicTrainMain
    do_training(*trainSessionParameters.getTupleForCnnTraining())
  File "/home/by354/mywork/testcode/Segmentation_myimplement/deepmedic-freezeLayers/deepmedic/trainValidateTestVisualiseParallel.py", line 1203, in do_training
    labelsForCentralOfSegmentsForSubepTrain] = parallelJobToGetDataForNextTraining() #fromParallelProcessing that had started from last loop when it was submitted.
TypeError: 'NoneType' object is not iterable

However, when I set numberTrainingSegmentsLoadedOnGpuPerSubep=1000 or 5000, it would run successfully.

Is anyone have the same problem?

**Comment by JavierCoronel** [comment]
Hi, I would say it is because of memory. Have you checked how much it costs load the 10K segments? You should also check the Batch Size for the number of optimization steps.

You can always run it with 5k and have no problem :)

Javier

**Comment by Kamnitsask** [comment]
Hello,

Thank you very much for the help Javier. I will agree. I also suspect memory problems, on your main RA, running out of it when the 10k segments are extracted. (They wouldn't fit in GPU memory either, but the problem hits duriong their extraction on the CPU). 

Depending on your data, possibly 10k segments could exceed 32GBs RAM I believe, possibly significantly more than this. Do an htop and see how much your RAM fills up during the segments-extraction phase.

I can see one useful reason to extract more segments per subepoch: To do more GPU processing after every round of loading from the disk (which can be slow). So, to balance CPU image loading with GPU processing and achieve the optimal usage of both vs wall-clock time. But for that, make sure your RAM can handle it. The default config is definitely not optimal for every machine, but was made to be somewhat good while affordable for even rather average machines. Further tinkering will need care from you :)

Thanks viridiu for your interest and feedback. Extra thanks to Javier for your help on this :)
Kostas

**Comment by viridyu** [comment]
Thank both of you very much. I guess it's the memory problem.
