### ISSUE TITLE
Error during training: "IndexError: index 779 is out of bounds for axis 1 with size 5"

### ISSUE THREAD

**Issue by SilvanaC** [Kamnitsask/deepmedic#61]
Hi:
I have mha files and I converted them to nii.gz using matlab (mha_read_header(), mha_read_volume() and MRIwrite(v,'name.nii','double')). However, this causes and error,  I think because some values in the header are diferent to the ones in the example images that you give.
So I was wondering how did you converted the files to nii.gz (which code)?

thanks for the help

**Comment by SilvanaC** [comment]
this is the error that I got:
![image](https://cloud.githubusercontent.com/assets/16765613/25075139/e4daa6a2-22d2-11e7-92df-e39fbbe3e714.png)

**Comment by Kamnitsask** [comment]
This does not seem to be related to mha->nii conversion. Note that, in the code, I never really use the headers of the niis.

The important lines in the error message are:
"IndexError: index 779 is out of bounds for axis 1 with size 5"
and the last one, showing that the error happened in the calculation of the negativeLogLikelihood.

I believe you have a problem with your ground-truth labels data, which are used for the calculation of the negativeLogLikelihood (training loss).

You have probably configured the model to have 5 output classes, but pass as a ground-truth label image something that at some voxel has a value 779 (see first error message I mentioned above).

Double check your ground truth labels. They should only include integer values, and no value larger than the number of classes you configured the model to have.

Regards,
Kostas

**Comment by Kamnitsask** [comment]
Finally, even if this is probably not an issue related to mha-to-nii conversion, I just pushed a script I used for such a conversion in case anyone interested (https://github.com/Kamnitsask/imgProcessingScripts)

**Comment by zihaozhu93** [comment]
@SilvanaC 
hi, the IndexError also happens to me, can you show me how to solve this problem? Thanks

**Comment by SilvanaC** [comment]
@zihaozhu93 
hi, as kamnitsask mentioned before, the error was due to the ground truth labels....  I had some volumenes that had a range higher than 4....  so I fixed my dataset.
