### ISSUE TITLE
few questions on whole flow

### ISSUE THREAD

**Issue by smileshot** [Kamnitsask/deepmedic#62]
@Kamnitsask 

Thanks for sharing your project.
I’m very interested in it

I saw a image below in your repository.

![](https://raw.githubusercontent.com/Kamnitsask/deepmedic/master/documentation/dmRes.png)

I have few questions.

1. What is the meaning of 4 (**4** x 25^3, **4** x 19^3) in "Input Segment"? Does it mean color space like RGB?

2. Would you explain how to make "normal resolution" and "low resolution" in "input segment". and Why use "low resolution"?

3. If I want to put our data in the "Input Segment", how should I structure the dimension.(**?** x 25^3, **?** x 19^3)

4. Can I get a script to create an "Input Segment"?

5. How to make the final result(Brain Lesion Segment Image)
As I think, to get the final result image(Brain Lesion Segment Image), Considering where 5 x 9^3 corresponds to the train image(Brain MRI, not Input Segment), and Overlapping 5 x 9^3

Thanks in advance

**Comment by Kamnitsask** [comment]
Hello,

I would appreciate if we keep the this issues-section of the github project for technical issues/bugs/feature suggestions.

For explanations on the algorithm, please check our paper (See beginning of documentation). 
For some explanations on how the software works, please have a look at the documentation.

A very quick reply to your questions:
1. They are 4 different MRI modalities used in BRATS. Indeed like RGB. You can configure a model to have as many input channels as you wish (see documentation).
2/3/4/5. The software does this internally. You just provide it with whole image volumes in nii format. See documentation for how to configure the software. See paper for how and why to tile the image in segments.

Kind regards,
Kostas
