### ISSUE TITLE
A simple question about BRATS challenges

### ISSUE THREAD

**Issue by Thatfreesky** [Kamnitsask/deepmedic#64]
Hello, Kamnitsask:

I am a beginner about this area. I use the following code to read the BRATS challenges data, but I do not know how to convert those files to the form of your example, because I do not know how to access the different part of the 'xxx.mha' files, especially I do not know how to fetch the ground truth information. 
![screenshot from 2017-04-23 20-51-25](https://cloud.githubusercontent.com/assets/15063337/25319082/2f9082ee-28cc-11e7-8411-371bc2b49886.png)
Consequently, can you guide me to solve this simple problem! It's better,if you can provide some script about process of the BRATS 'xxx.mha' file. Then we can study the important pipeline, which is useful for lots of beginners like me. Do not need to worry about such script can no run on our devices, we can study the idea by reading the code.

Thanks for your help!

**Comment by Kamnitsask** [comment]
Hi,

You are correctly accessing the image contents.
The ground truth segmentation is a completely separate file. Look for it in the folder with your brats data.
mha to nii.gz conversion scripts pushed at (https://github.com/Kamnitsask/imgProcessingScripts) for your reference (wont be supporting them, just for reference).

I cannot be providing support here for data processing and manipulation here, sorry. I am trying to keep up with deepmedic's technical issues, which this part is for. Please consult documentation of relevant libraries such as sitk/itk. There are quite some resources online.

Kind regards,
Kostas

**Comment by Thatfreesky** [comment]
Hello, Kamnitsask:

Thanks for your help and I have found the ground truth files.
