### ISSUE TITLE
how to annotate the image ? 

### ISSUE THREAD

**Issue by sxzy** [Kamnitsask/deepmedic#67]
Oh ,I have a question here.I m wondering how you annotate the image?circle the edge?

**Comment by Kamnitsask** [comment]
manually using some tool for such purpose. I cannot direct you to such tools, probably some radiologist that has done this before is more appropriate. Commonly, detailed annotations are needed. Not just circles.

Excuse the brevity, but this is not a deepmedic-related issue. You should rather look this information to related literature and sources.

Kind regards,
Kostas
