### ISSUE TITLE
TypeError: object of type 'bool' has no len()

### ISSUE THREAD

**Issue by tuttoweb** [Kamnitsask/deepmedic#68]
I was training deepmedic with ISLES data usign full resolution, but something stopped the training:

> SAVING: Epoch #4 finished. Saving CNN model.
> Saving network to: /home/s1582461/scratch/deepmedic/examples/output/cnnModels/trainSessionDeepMedicOriginal/deepMedicOriginal.trainSessionDeepMedicOriginal.2017-05-24.20.20.37.320483.save
> Model saved.
> TIMING: The whole Epoch #4 took time: 2287.47(s)
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ End of Training Epoch. Model was Saved. ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ***Starting validation with Full Inference / Segmentation on validation subjects for Epoch #4...***
> ###########################################################################################################
> ############################# Starting full Segmentation of Validation subjects ##########################
> ###########################################################################################################
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ~~~~~~~~~~~~~~~~~~~~ Segmenting subject with index #0 ~~~~~~~~~~~~~~~~~~~~
> Loading subject with 1st channel at: /home/s1582461/scratch/deepmedic_full_size/VFlair/10.nii.gz
> Starting to (tile) extract Segments from the images of the subject for Segmentation...
> Finished (tiling) extracting Segments from the images of the subject for Segmentation.
> Starting to segment each image-part by calling the cnn.cnnTestModel(i). This part takes a few mins per volume...
> Total number of Segments to process:390
> Processed 0/390 Segments.
> Processed 70/390 Segments.
> Processed 140/390 Segments.
> Processed 210/390 Segments.
> Processed 280/390 Segments.
> Processed 350/390 Segments.
> TIMING: Segmentation of this subject: [Extracting:] 0.119999999995 [Loading:] 0.0100000000002 [ForwardPass:] 45.36 [Total:] 45.49(s)
> Saving the new label (segmentation) image for the subject #0
> Image saved at: /home/s1582461/scratch/deepmedic/examples/output/predictions/trainSessionDeepMedicOriginal/predictions/val_22_Segm.nii.gz
> Traceback (most recent call last):
>   File "./deepMedicRun", line 102, in <module>
>     deepMedicTrain.deepMedicTrainMain(absPathToTrainConf, absPathToCnnModelGivenInCmdLine, cnnInstanceLoaded, filenameAndPathWhereNewlyCreatedModelWasSaved)
>   File "/exports/eddie/scratch/s1582461/deepmedic/deepmedic/frontEndModules/deepMedicTrain.py", line 449, in deepMedicTrainMain
>     do_training(*trainSessionParameters.getTupleForCnnTraining())
>   File "/exports/eddie/scratch/s1582461/deepmedic/deepmedic/trainValidateTestVisualiseParallel.py", line 1443, in do_training
>     listOfNamesToGiveToFmVisualisationsIfSaving=listOfNamesToGiveToFmVisualisationsIfSaving
>   File "/exports/eddie/scratch/s1582461/deepmedic/deepmedic/trainValidateTestVisualiseParallel.py", line 1782, in performInferenceForTestingOnWholeVolumes
>     if (len(savePredictionImagesSegmentationAndProbMapsList[1]) >= class_i + 1) and (savePredictionImagesSegmentationAndProbMapsList[1][class_i] == True) : #save predicted probMap for class
> TypeError: object of type 'bool' has no len()
> 

I had trained deepmedic in the past and usually I can debug normal errors, but I've never seen this one.
Any help would be appreciated.
Best
vg

**Comment by Kamnitsask** [comment]
Hello,

Could you please check what value you are giving to the variable "saveProbMapsForEachClassVal" in the trainConfig.cfg file?

It should be a list, with one boolean per class of the task. eg: saveProbMapsForEachClassVal = [True, True, True, True, True]

I am guessing you passed something like = True or = False.

Regards,
Kostas

**Comment by tuttoweb** [comment]
Dear Kostas,
thank you very much for your support. It's working fine

Ευχαριστώ
vg
