### ISSUE TITLE
Deepmedic Throws Error On ppworker.py at training

### ISSUE THREAD

**Issue by AyushKarnawat** [Kamnitsask/deepmedic#7]
Hi ,

I have been trying to work with the deepmedic package on HPC using gpu. The example with the full network runs absolutely fine. However, now I am trying our set of TCIA GBM and LGG cases with the same algorithm i.e. that is replacing the training and validation .cfg files with our cases. I think done this correctly, but the training phase throws an error at ppworker.py showing a problem with the index size. I'm copying the error below for your reference. I would appreciate your help on this.

-Ayush Karnawat

=============================================================
=======================================================
============== Training the CNN model =================
=======================================================
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~Starting new Epoch! Epoch #0/35 ~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
**************************************************************************************************
************* Starting new Subepoch: #0/20 *************
**************************************************************************************************
:=:=:=:=:=:=:=:=: Starting to extract Segments from the images for next Validation... :=:=:=:=:=:=:=:=:
Out of the 4 subjects given for Validation, it was specified to extract Segments from 4 per subepoch.
Shuffled indices of subjects that were randomly chosen: [1, 0, 2, 3]
SAMPLING: Starting iterations to extract Segments from each image for next Validation...
SAMPLING: Going to load the images and extract segments from the subject (iteration) #0/4
Loading subject with 1st channel at:/home/axk840/deepmedic/examples/dataForExamples/patientTestingData/validation/TCGA-06-0125/MNISpace/FLAIR_BiasCorrect_Normalized_Reg_MNI_MeanDivStd.nii.gz
DEBUG: Original index of this case in list of subjects: 1
Images for subject loaded.
From current subject #0 extracting that many Segments centered on : Foreground=0 Background:1250
WARN: No mask was provided for the foreground (Ground Truth Labels). In this case, Background-Centered segments are actually extracted from the whole ROI in a UNIFORM manner (thus extracting Foreground-Centered too). This is a hacked implementation, which will be re-written cleaner soon.
End of the function that extracts segments. Segments extracted centered on: Foreground=0 Background=1250
SAMPLING: Going to load the images and extract segments from the subject (iteration) #1/4
Loading subject with 1st channel at:/home/axk840/deepmedic/examples/dataForExamples/patientTestingData/validation/TCGA-02-0054/MNISpace/FLAIR_BiasCorrect_Normalized_Reg_MNI_MeanDivStd.nii.gz
DEBUG: Original index of this case in list of subjects: 0
Images for subject loaded.
From current subject #1 extracting that many Segments centered on : Foreground=0 Background:1250WARN: No mask was provided for the foreground (Ground Truth Labels). In this case, Background-Center
ed segments are actually extracted from the whole ROI in a UNIFORM manner (thus extracting Foregroun
d-Centered too). This is a hacked implementation, which will be re-written cleaner soon.
End of the function that extracts segments. Segments extracted centered on: Foreground=0 Background=
1250
SAMPLING: Going to load the images and extract segments from the subject (iteration) #2/4
Loading subject with 1st channel at:/home/axk840/deepmedic/examples/dataForExamples/patientTestingData/validation/TCGA-FG-5964/MNISpace/FLAIR_BiasCorrect_Normalized_Reg_MNI_MeanDivStd.nii.gz
DEBUG: Original index of this case in list of subjects: 2
Images for subject loaded.
From current subject #2 extracting that many Segments centered on : Foreground=0 Background:1250
WARN: No mask was provided for the foreground (Ground Truth Labels). In this case, Background-Centered segments are actually extracted from the whole ROI in a UNIFORM manner (thus extracting Foreground-Centered too). This is a hacked implementation, which will be re-written cleaner soon.
End of the function that extracts segments. Segments extracted centered on: Foreground=0 Background=1250
SAMPLING: Going to load the images and extract segments from the subject (iteration) #3/4
Loading subject with 1st channel at:/home/axk840/deepmedic/examples/dataForExamples/patientTestingData/validation/TCGA-FG-6692/MNISpace/FLAIR_BiasCorrect_Normalized_Reg_MNI_MeanDivStd.nii.gz
DEBUG: Original index of this case in list of subjects: 3
Images for subject loaded.
From current subject #3 extracting that many Segments centered on : Foreground=0 Background:1250
WARN: No mask was provided for the foreground (Ground Truth Labels). In this case, Background-Centered segments are actually extracted from the whole ROI in a UNIFORM manner (thus extracting Foreground-Centered too). This is a hacked implementation, which will be re-written cleaner soon.
End of the function that extracts segments. Segments extracted centered on: Foreground=0 Background=1250
TIMING: Extracting all the Segments for next Validation took time: 6.15(s)
:=:=:=:=:=:=:=:=: Finished extracting Segments from the images for next Validation. :=:=:=:=:=:=:=:=:
Loading Validation data for subepoch #0 on shared variable...
DEBUG: For Validation, loading to shared variable that many Segments: 5000
TIMING: Loading sharedVariables for Validation in epoch|subepoch=0|0 took time: 0.19(s)
PARALLEL: Before Validation in subepoch #0, the parallel job for extracting Segments for the next Training is submitted.
-V-V-V-V-V- Now Validating for this subepoch before commencing the training iterations... -V-V-V-V-V-
Validated on 0/104 of the batches for this subepoch...
Validated on 20/104 of the batches for this subepoch...
Validated on 40/104 of the batches for this subepoch...
Validated on 60/104 of the batches for this subepoch...
Validated on 80/104 of the batches for this subepoch...
Validated on 100/104 of the batches for this subepoch...
++++++++++++++++ Reporting Accuracy over whole subepoch for (whole-foreground)Class-0 ++++++++++++++++
VALIDATION: Epoch #0, Subepoch #0, (whole-foreground)Class-0: mean error: 0.996995
VALIDATION: Epoch #0, Subepoch #0, (whole-foreground)Class-0: mean accuracy 0.00300481
VALIDATION: Epoch #0, Subepoch #0, (whole-foreground)Class-0: mean accuracy for Positive Samples(voxels): 1.0. True Predicted Pos=37/37
VALIDATION: Epoch #0, Subepoch #0, (whole-foreground)Class-0: mean accuracy for Negative Samples(voxels): 0.00282543. True Predicted Neg=14/4955
VALIDATION: Epoch #0, Subepoch #0, (whole-foreground)Class-0: mean Dice: 0.0147557
VALIDATION: Epoch #0, Subepoch #0, Class-1: mean error: 0.996995
VALIDATION: Epoch #0, Subepoch #0, Class-1: mean accuracy 0.00300481
VALIDATION: Epoch #0, Subepoch #0, Class-1: mean accuracy for Positive Samples(voxels): 0.0. True Predicted Pos=0/14
VALIDATION: Epoch #0, Subepoch #0, Class-1: mean accuracy for Negative Samples(voxels): 1.0. True Predicted Neg=4978/4978
VALIDATION: Epoch #0, Subepoch #0, Class-1: mean Dice: 0.0
++++++++++++++++ Reporting Accuracy over whole subepoch for Class-2 ++++++++++++++++
VALIDATION: Epoch #0, Subepoch #0, Class-2: mean error: 0.996995
VALIDATION: Epoch #0, Subepoch #0, Class-2: mean accuracy 0.00300481
VALIDATION: Epoch #0, Subepoch #0, Class-2: mean accuracy for Positive Samples(voxels): 0.0. True Predicted Pos=0/8
VALIDATION: Epoch #0, Subepoch #0, Class-2: mean accuracy for Negative Samples(voxels): 1.0. True Predicted Neg=4984/4984
VALIDATION: Epoch #0, Subepoch #0, Class-2: mean Dice: 0.0
++++++++++++++++ Reporting Accuracy over whole subepoch for Class-3 ++++++++++++++++
VALIDATION: Epoch #0, Subepoch #0, Class-3: mean error: 0.996995
VALIDATION: Epoch #0, Subepoch #0, Class-3: mean accuracy 0.00300481
VALIDATION: Epoch #0, Subepoch #0, Class-3: mean accuracy for Positive Samples(voxels): 1.0. True Predicted Pos=1/1
VALIDATION: Epoch #0, Subepoch #0, Class-3: mean accuracy for Negative Samples(voxels): 0.00280505. True Predicted Neg=14/4991
VALIDATION: Epoch #0, Subepoch #0, Class-3: mean Dice: 0.000401687
++++++++++++++++ Reporting Accuracy over whole subepoch for Class-4 ++++++++++++++++
VALIDATION: Epoch #0, Subepoch #0, Class-4: mean error: 0.996995
VALIDATION: Epoch #0, Subepoch #0, Class-4: mean accuracy 0.00300481
VALIDATION: Epoch #0, Subepoch #0, Class-4: mean accuracy for Positive Samples(voxels): 0.0. True Predicted Pos=0/14
VALIDATION: Epoch #0, Subepoch #0, Class-4: mean accuracy for Negative Samples(voxels): 1.0. True Predicted Neg=4978/4978
VALIDATION: Epoch #0, Subepoch #0, Class-4: mean Dice: 0.0
TIMING: Validating on the batches of this subepoch #0 took time: 41.61(s)
UPDATE: In this last epoch (cnnTrained) #0 the CNN achieved a new highest mean validation accuracy of :0.00015024
:=:=:=:=:=:=:=:=: Starting to extract Segments from the images for next Training... :=:=:=:=:=:=:=:=:
Out of the 10 subjects given for Training, it was specified to extract Segments from 50 per subepoch.
Shuffled indices of subjects that were randomly chosen: [7, 8, 3, 0, 4, 9, 2, 1, 6, 5]
SAMPLING: Starting iterations to extract Segments from each image for next Training...
SAMPLING: Going to load the images and extract segments from the subject (iteration) #0/10
Loading subject with 1st channel at:/home/axk840/deepmedic/examples/dataForExamples/patientTestingData/train/TCGA-DU-7309/MNISpace/FLAIR_BiasCorrect_Normalized_Reg_MNI_MeanDivStd.nii.gz
/home/axk840/anaconda2/lib/python2.7/site-packages/pp-1.6.4-py2.7.egg/ppworker.py:78: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  try:
DEBUG: Original index of this case in list of subjects: 7
Images for subject loaded.
From current subject #0 extracting that many Segments centered on : Foreground=50 Background:50
/home/axk840/anaconda2/lib/python2.7/site-packages/pp-1.6.4-py2.7.egg/ppworker.py:32: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  import sys
/home/axk840/anaconda2/lib/python2.7/site-packages/pp-1.6.4-py2.7.egg/ppworker.py:33: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  import os
/home/axk840/anaconda2/lib/python2.7/site-packages/pp-1.6.4-py2.7.egg/ppworker.py:39: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  version = "1.6.4"
/home/axk840/anaconda2/lib/python2.7/site-packages/pp-1.6.4-py2.7.egg/ppworker.py:40: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

/home/axk840/anaconda2/lib/python2.7/site-packages/pp-1.6.4-py2.7.egg/ppworker.py:43: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 528 but corresponding boolean dimension is 209
  fname, fsources, imports = pickle.loads(msg)
An error has occured during the function execution
Traceback (most recent call last):
  File "/home/axk840/anaconda2/lib/python2.7/site-packages/pp-1.6.4-py2.7.egg/ppworker.py", line 90, in run
    __result = __f(*__args)
  File "<string>", line 150, in getTheArraysOfImageChannelsAndLesionsToLoadToGpuForSubepoch
  File "<string>", line 43, in get_positive_and_negative_imageParts
IndexError: index 130 is out of bounds for axis 2 with size 96
Traceback (most recent call last):
  File "/home/axk840/deepmedic/deepMedicRun", line 102, in <module>
    deepMedicTrain.deepMedicTrainMain(absPathToTrainConf, absPathToCnnModelGivenInCmdLine, cnnInstanceLoaded, filenameAndPathWhereNewlyCreatedModelWasSaved)
  File "/home/axk840/deepmedic/deepmedic/frontEndModules/deepMedicTrain.py", line 440, in deepMedicTrainMain
    do_training(*trainSessionParameters.getTupleForCnnTraining())
  File "/home/axk840/deepmedic/deepmedic/trainValidateTestVisualiseParallel.py", line 1434, in do_training
    subsampledImagePartsChannelsToLoadOnGpuForSubepochTraining] = parallelJobToGetDataForNextTraining() #fromParallelProcessing that had started from last loop when it was submitted.
TypeError: 'NoneType' object is not iterable

**Comment by Kamnitsask** [comment]
Hello Ayush and thanks a lot for the feedback and interest in our work. Hope you find it useful. 

About the problem:

The ppworker is a parallel process that is handling the extraction of image-patches/segments for the training and validation. If anything goes wrong during this process, it will be breaking and complaining.

- I think the explanation about the problem lies in the line: "IndexError: index 130 is out of bounds for axis 2 with size 96".
I believe that for this subject: /home/axk840/deepmedic/examples/dataForExamples/patientTestingData/train/TCGA-DU-7309/MNISpace/FLAIR_BiasCorrect_Normalized_Reg_MNI_MeanDivStd.nii.gz
the input images are not all of the same dimensions. Check that the actual images (MRI/CT/whatever), the ground-truth labels and the rois are all of the same dimensions (probably one of them is at axis 2 of size 96, and all others are bigger?). The software needs all of them to be of the same size for a certain subject (not required across all subjects. Per-subject basis only).

Please check if this was the problem and let me know.

ps: This warning "FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison" is ugly and my bad. I will open an issue for this.

Thanks again for your interest and feedback. Let me know how it goes.

Kind regards,
Konstantinos

**Comment by AyushKarnawat** [comment]
Hi Kamnitsask,

Sorry for getting back to you so late. The fix you described worked perfectly as the brain mask was not of the same dimensions as the Flair,T1,GT, and ROI files for a per-subject basis. After modifying the brain masks to be the same dimension, the training and testing models ran successfully. Thank you once again for your help.

-Ayush

**Comment by Kamnitsask** [comment]
Wonderful to hear your problem is solved Ayush. Hope you get some helpful results for your work from it. 

Sorry for the fuss it might have caused you. I know that I should have placed better checks and error messages with feedback, but there are quite some things to check for and this would be quite some work, which is lower in my priorities. Quite some things to do before this.

Please feel free to let me know how your experience with it goes, or ask anything further at konstantinos.kamnitsas12@imperial.ac.uk

Kind regards,
Kostas
