### ISSUE TITLE
The deepMedicRun has SyntaxError

### ISSUE THREAD

**Issue by 939706171** [Kamnitsask/deepmedic#71]
(theano) sty@styr:~/deepmedic$$ ./deepMedicRun -h
  File "./deepMedicRun", line 64
    if devArg <> "cpu" and devArg <> "gpu" and not (devArg.startswith("gpu") and strIsInt(devArg[3:]) ) :
               ^
SyntaxError: invalid syntax

I cant solve the problem.what can i do?The envinroment wrong or opeartion wrong?

**Comment by Kamnitsask** [comment]
Hello,

Are you using python2 or python3?

K

**Comment by Kamnitsask** [comment]
Closing as there was no update.

**Comment by mnimmagari** [comment]
using python3 got the same error any solution pls

**Comment by Kamnitsask** [comment]
code was written in python2. For python3, try branch "python3compat".

**Comment by Jesse-Back** [comment]
@Kamnitsask hi i got same issue on v0.5.4.
and, there is no branch named  "python3compat"
so, what can i do
