### ISSUE TITLE
A little question about normalizing the intensity of the data

### ISSUE THREAD

**Issue by Thatfreesky** [Kamnitsask/deepmedic#72]
Hi kamnitsask,

Thanks for your powerful model, It helps me a lot.
But, I have a little question when I follow your suggestion to normalize the data. For checking whether my normalizing method is right, I use the original brats2015 training data to normalize which corresponds your example file. Here is my code.
First, I read the chosen file and your example file.
```python
In [1]: import nibabel as nib
   ...: import numpy as np
   ...: import SimpleITK as sitk
   ...: 

In [2]: exampleFile = '/home/mountain/Desktop/\
   ...: deepmedic-read/examples/dataForExamples\
   ...: /brats2015TrainingData/train/brats_2013_pat0005_1/T1c_subtrMeanDivStd.nii.gz'

In [3]: chosenFile = '/home/mountain/Desktop/\
   ...: BrainNets/data/BRATS2015_Training/HGG/\
   ...: brats_2013_pat0005_1/VSD.Brain.XX.O.MR_T1c.54538/VSD.Brain.XX.O.MR_T1c.54538.mha'

In [4]: exampleFileArray = nib.load(exampleFile).get_data()

In [5]: chosenFileImage = sitk.ReadImage(exampleFile)

In [6]: chosenFileArray = sitk.GetArrayFromImage(chosenFileImage)

In [7]: exampleFileArray.shape
Out[7]: (240, 240, 155)

In [8]: chosenFileArray.shape
Out[8]: (155, 240, 240)

In [9]: chosenFileArrayT = np.transpose(chosenFileArray, (1, 2, 0))

In [10]: chosenFileArrayT.shape
Out[10]: (240, 240, 155)
```
Than I normalize the chosen file

```python
In [11]: normedChosenFileArrayT = (chosenFileArrayT - np.mean(chosenFileArrayT)) / np.std(chosenFileArray
    ...: T)

In [12]: normedChosenFilePatch = normedChosenFileArrayT[120:125, 120:125, 75]

In [13]: exampleFilePatch = exampleFileArray[120:125, 120:125, 75]

In [14]: normedChosenFilePatch
Out[14]: 
array([[ 1.21521699,  1.30665469,  1.6781199 ,  2.14673758,  2.40390563],
       [ 1.66097522,  1.80956125,  2.02101064,  2.40962052,  2.43819475],
       [ 1.65526044,  1.81527627,  2.11816335,  2.4267652 ,  2.30675316],
       [ 1.39237738,  1.53524864,  1.87813962,  2.3010385 ,  2.38676119],
       [ 1.20378733,  1.47238529,  1.83242071,  2.2553196 ,  2.46676898]], dtype=float32)

In [15]: exampleFilePatch
Out[15]: 
array([[-1.21323407, -0.60059661, -0.60845095, -0.96974993, -1.22894275],
       [-1.08756483, -0.39638412, -0.38852981, -0.77339178, -0.85978937],
       [-0.57703364, -0.10577405,  0.02774949, -0.30213222, -0.36496681],
       [ 0.06702112,  0.42832014,  0.45188311,  0.27908793,  0.21625333],
       [ 0.4204658 ,  0.46759176,  0.28694227,  0.39690283,  0.50686342]], dtype=float32)
```
The result shows those two array are different. I guess whether those two files are not corresponding, so I decide to check the mean of the two files
```python
In [16]: np.mean(normedChosenFileArrayT)
Out[16]: -1.0351284e-05

In [17]: np.mean(exampleFileArray)
Out[17]: -2.8833938
```
So, I want to know whether my normalizing method is right. If the answer is Yes, why we get different results. If the answer is No, can you tell me how you normalize the data.
Thanks.

**Comment by Kamnitsask** [comment]
Hello,

Thanks a lot for your interest and kind words.

First, if you can extract an ROI as a preprocessing step, which is the area where you are interested to train and apply the CNN, then you should be normalizing wrt the mean and std of the intensities within the ROI. At least this is the practice that I had best success with.

Eg, for brains, usually the ROI is the brainmask. Check the brainmasks I give with the examples ;) I normalize all voxels of the image, but with the mean and std computed taking into account only the voxels in the brainmask.

This is not CNN specific, but in many problems it's good practice, and I try to do it, so don't worry if you see small differences with my normalized images and yours: When I calculate mean/std I try to first exclude the voxels with too high and too low intensities. Outliers that can influence the mean/std a lot. This can be done by excluding everything eg below and above the 5th/95th percentile of the images histogram (under the ROI mask).

Hope the above help.

Kostas

**Comment by Kamnitsask** [comment]
Adding here a pointer to related answer to issue #56
