### ISSUE TITLE
IndexError when validation is set True

### ISSUE THREAD

**Issue by anandpreshob** [Kamnitsask/deepmedic#75]
Hi,
For training, when the Validation Flag is set true:
performValidationOnSamplesThroughoutTraining = True
Deepmedic fails to train the model and gives a indexerror:
The CNN model was loaded successfully from: ./deepmedic/examples/output/cnnModels/deepmedic_5subject.initial.2017-06-13.17.47.20.044230.save
Traceback (most recent call last):
  File "./deepMedicRun", line 134, in <module>
    deepMedicTrain.deepMedicTrainMain(absPathToTrainConf, absPathToCnnModelGivenInCmdLine, cnnInstanceLoaded, filenameAndPathWhereNewlyCreatedModelWasSaved, args.reset_optimizer)
  File "./deepmedic/deepmedic/frontEndModules/deepMedicTrain.py", line 474, in deepMedicTrainMain
    padInputImagesBool = configGet(trainConfig.PAD_INPUT)
  File "./deepmedic/deepmedic/frontEndModules/frontEndHelpers/trainParametersClass.py", line 375, in __init__
    self._makeFilepathsForPredictionsAndFeaturesVal( folderForPredictionsVal, folderForFeaturesVal )
  File "./deepmedic/deepmedic/frontEndModules/frontEndHelpers/trainParametersClass.py", line 435, in _makeFilepathsForPredictionsAndFeaturesVal
    filepathForCasePrediction = absPathToFolderForPredictionsFromSession + "/" + self.namesToSavePredictionsAndFeaturesVal[case_i]
IndexError: list index out of range

**Comment by Kamnitsask** [comment]
Hi,

Did you make sure that the file you provide with how to name the prediction-files have 1 entry for each validation subject?

(eg see file examples/configFiles/deepMedic/train/validation/validationNamesOfPredictions.cfg)

**Comment by anandpreshob** [comment]
Hi,
Guess that solved the issue.
Thank you
