### ISSUE TITLE
something wrong when using gpu

### ISSUE THREAD

**Issue by 94mia** [Kamnitsask/deepmedic#77]
Hi, Kostas

I encountered something strange. I run the code following the steps of Tutorial (https://github.com/Kamnitsask/deepmedic/) without changing anything . Ｗhen I use gpu and get nan cost. But if I use cpu , it runs correctly. 
I don't know why. 

My theano version is 0.90.
gpu: NVIDIA geforce gtx 1081ti
cuda 8.0 , cudnn v4

Mia

**Comment by Kamnitsask** [comment]
Hello,

Thanks for the feedback. It's the second time that I see something like this reported from users. It has never happened to me but now I am worried and I will investigate. Please have a look a similar issue: https://github.com/Kamnitsask/deepmedic/issues/76 meanwhile, it may help you solve the problem.

Let me know if it helps

I will also try to investigate with similar software versions+hardware.

Thanks a lot for the feedback and sorry for the inconvenience.
Kostas

**Comment by 94mia** [comment]
Thanks for your reply. I fixed this by changing the old backend(cuda) to new backend(libgpuarray).
