### ISSUE TITLE
Great job

### ISSUE THREAD

**Issue by multithink** [Kamnitsask/deepmedic#78]
Hi Kostas

I am a research fellow in computational biomechanics of cardiovascular systems. I was looking for some way to automate the segmentation process using deep learning. Your work is one of the best and easy to follow. I am glad that you made it possible for new users to work in this field.

My question is, if I could use this code for segmenting cardiovascular regions, like heart and vessels? 

Also, which tool you use for viewing the results for NIFF format?

Regards

Agha Shiraz

**Comment by Kamnitsask** [comment]
Hi,

thanks for your interest and kind words.

I have previously used it for segmentation of the heart. That's definitely fine and competitive with the state of the art methods. I have little-to-no experience about the vessels, so I cannot accurately comment on this. If you could provide some more information about the task, eg size of the images, type of images, what vessels, perhaps I could estimate. Try emailing me some pictures and info.

K
