### ISSUE TITLE
How to  manually add the paths to the folders containing these files in your environment's variables.

### ISSUE THREAD

**Issue by haoxiaodao** [Kamnitsask/deepmedic#80]
I am a novice in using the ubuntu operating system, I do not know how to use the "setenv" command, and 
What are the parameters of the "setenv" command?
Thanks.

**Comment by Kamnitsask** [comment]
Excuse me for the brevity, but I can't explain this in detail here.

Using setenv you ll need to add the paths to the necessary cuda folders and files, as commenting in the documentation.

Try to google: "unix setenv command", "unix environment variables" and cuda-related information to find what exactly you ll need to add to your path and how.

You should google this info regardless the use of deepmedic, you should learn how to set-up your unix environment. This is basic and super-important stuff.

K
