### ISSUE TITLE
Weight for each channel

### ISSUE THREAD

**Issue by Audy322** [Kamnitsask/deepmedic#82]
Hi Kamnitsask, 

It might be a silly question but is it possible to change the "weight" of the different channels ?
As example if my 3DT1 image should give more relevant informations than the Flair one, I would give a weight of 0.7 to the 3DT1 images and 0.3 to the Flair.

Thanks in advance.

**Comment by Kamnitsask** [comment]
In standard network systems, the "weight" of each channel is essentially learnt during training via learning the kernel weights.

If you d like to do it somehow differently, eg manually or more ellaborately, then that's a totally self-contained research project. There is no "standard way" to do it.

K
