### ISSUE TITLE
How to set multigpu tranining/testing?

### ISSUE THREAD

**Issue by venus024** [Kamnitsask/deepmedic#85]
Hi, kamnitsask:
    Thanks for your great work. Now I am training a segmentation task use the deepmedic tool. However, i CANNOT use multi-gpu to train my task. For example, if I have four gpus, I can only run my job properly with the gpu parameters set as: "gpu0" or "gpu1" or "gpu2" or "gpu3". So do you have any advice how can i use four gpus to train my work? 
   Thank you very much!
BRs!
Venus

**Comment by Kamnitsask** [comment]
Hello and sorry for the super-delayed reply. I ve been seriously overwhelmed and failed to keep up with issues. I hope I ll be able to support / keep updating this project better from now on again.

Multi-gpu was added with 0.9 theano which I haven't integrated to yet. So, currently, this project is single gpu only. Supporting theano 0.9 and 0.10 is the first thing I ll do, so I ll update you soon on how this goes.

Sorry again for the super slow reply.
Kostas
