### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by huanzhou94** [Kamnitsask/deepmedic#87]
Hi Kostas,

I got this NonType error and don't know what to do. 

I look through your answer to "ValueError: could not broadcast input array from shape (34,34,34) into shape (1) at start of training#70", because it also returned as a NonType error. However, after I adjusted train image segment size, it gave me 'ValueError'. 

I tried to train with only 2 train-sets, it works fine, but if I increased the number of train-sets to 102, it returned me with this kind of error. You got any idea what's resulting this?

* All my train-sets have same voxels: 512x512x512, and same dimensions: 0.43x0.43x4.69844 mm

Traceback (most recent call last):
  File "./deepMedicRun", line 135, in <module>
    deepMedicTrain.deepMedicTrainMain(absPathToTrainConf, absPathToCnnModelGivenInCmdLine, cnnInstanceLoaded, filenameAndPathWhereNewlyCreatedModelWasSaved, args.reset_optimizer)
  File "/home/hzhou/Desktop/deepmedic-master/deepmedic/frontEndModules/deepMedicTrain.py", line 497, in deepMedicTrainMain
    do_training(*trainSessionParameters.getTupleForCnnTraining())
  File "/home/hzhou/Desktop/deepmedic-master/deepmedic/trainValidateTestVisualiseParallel.py", line 1207, in do_training
    [channsOfSegmentsForSubepPerPathwayTrain, labelsForCentralOfSegmentsForSubepTrain] = parallelJobToGetDataForNextTraining() #fromParallelProcessing that had started from last loop when it was submitted.
TypeError: 'NoneType' object is not iterable

Regards,
Zhou Huan

**Comment by Kamnitsask** [comment]
Hi Zhou,

Sorry for the late reply, too busy schedule and I fail following all emails. Thank you very much for your interest in our work.

If the code runs for a few datasets but not for all, I strongly believe there is some inconsistency in one/some of your datasets. Check that all volumes, rois, gt labels have same dimensions. Also check that the ROI is not entirely 0 for some dataset.

K
