### ISSUE TITLE
How to convert the data？

### ISSUE THREAD

**Issue by HrsPythonix** [Kamnitsask/deepmedic#89]
I want to use BRATS 2015 to do the training, but it is mha format, any idea how to convert it into the data that suits deepmedic?

**Comment by mingrui** [comment]
I have a similar problem, the data preprocessing section on the wiki doesn't make it very clear for beginners.

I have found similar libraries that have included preprocessing scripts as a reference to get started:
https://github.com/ellisdg/3DUnetCNN

**Comment by mingrui** [comment]
https://github.com/Kamnitsask/deepmedic/issues/43
