### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by poyukao** [Kamnitsask/deepmedic#9]
Hello,

For deepMedicLess, I changed the [numberOfInputChannels = 1] in the model creating configuration file, and I was able to get the parameters for the initial deepMedicLess model. 

Then, I changed the [channelsTraining = "./trainCHannels_t1c.cfg"] and [channelsTraining = "./trainCHannels_t1c.cfg"] to training configuration file. And I got the error:

Traceback (most recent call last):
  File "./deepMedicRun", line 102, in <module>
    deepMedicTrain.deepMedicTrainMain(absPathToTrainConf, absPathToCnnModelGivenInCmdLine, cnnInstanceLoaded, filenameAndPathWhereNewlyCreatedModelWasSaved)
  File "/home/pkao/deepmedic/deepmedic/frontEndModules/deepMedicTrain.py", line 319, in deepMedicTrainMain
    listOfAListPerChannelWithFilepathsOfAllCasesTrain = [parseAbsFileLinesInList(getAbsPathEvenIfRelativeIsGiven(channelConfPath, trainConfigFilepath)) for channelConfPath in configGet(trainConfig.CHANNELS_TR)]
  File "/home/pkao/deepmedic/deepmedic/frontEndModules/frontEndHelpers/parsingFilesHelpers.py", line 41, in parseAbsFileLinesInList
    with open(pathToListingFile, "r") as inp :
IOError: [Errno 21] Is a directory: '/home/pkao/deepmedic/examples/configFiles/deepMedicLess/train'

I only want to use one channel to train the network. Could you help me to solve this problem?

Best,
Po-Yu Kao

**Comment by Kamnitsask** [comment]
Hello,

First make sure you are giving the parameter correctly. channelsTraining gets a list. In your case, a list with one string. And not just a string as you showed in your message:
channelsTraining = ["./trainCHannels_t1c.cfg"]

Let me know how this goes.

**Comment by poyukao** [comment]
Hi,

It works now. I appreciate for your assistant.
