### ISSUE TITLE
Strange messages while running the testing 

### ISSUE THREAD

**Issue by pykao** [Kamnitsask/deepmedic#94]
Hi,

I am using gpu to run the testing part. It worked but I got an strange messages:

CONFIG: Theano is using the [GPU].
CONFIG: Theano found and will use cuDNN [False]

What does it mean by False in above? I did not use cuDNN?

Best,
Po-Yu

**Comment by Kamnitsask** [comment]
Nope, this "False" means that Theano has not detected CuDNN and thus you are not using it. Ensure that cudnn files are in folders that are visible within your environment. See section 1.3 of deepmedic's documentation, and you can further find info on nvidia's sites about installing correctly cudnn.

Cheers
