### ISSUE TITLE
Ground Truth Files For BRATS 2015 Test Data

### ISSUE THREAD

**Issue by ZeinabSalkhorde** [Kamnitsask/deepmedic#96]
Hi
Dear Mr.  Kamnitsas
 Thanks for your great work. Now I studied your high quality papers "DeepMedic for Brain Tumor Segmentation" and "Efficient Multi-Scale 3D CNN with Fully Connected CRF for Accurate Brain Lesion Segmentation". I used your software available at https://github.com/Kamnitsask/deepmedic. In this regard, we want to test your model on the public benchmarks BRATS2015, I downloaded BRATS2015 from https://www.smir.ch/. The training data was complete but the test data does not have ground truth files. Since you have achieved the state-of-the-art result in this competition, So do you have  the ground truth files for BRATS 2015 test data?  Please, can you get these files? Or do you know how we can access these files ?

,Very truly yours

Zeinab Salkhorde

**Comment by Kamnitsask** [comment]
Hello,

Thank you for your kind words and your interest in our work.

This is not however an issue relevant to this codebase. I cannot be providing data, nor is this part of the deepmedic project i am afraid. Information regarding data should be found in the corresponding papers, and requests about them should best be addressed to the relevant organizers. Please help me maintain this project by keeping the issues' section for issues on the codebase and its functionality.

The above being said, ground truth data of the "test" subset are not to be released by the organizers. Use the online evaluation platform instead.

Kind regards,
Kostas
