### ISSUE TITLE
Merge models from cross validation

### ISSUE THREAD

**Issue by Sichtermann** [Kamnitsask/deepmedic#97]
Hi Konstantinos,
thanks for your work and support!
I have an issue: let's say I split my data into 5 subsets, including test/train/validation per subset for doing cross validation. Now I trained the network on each subset seperately and got different results for the individually trained models.
Is there a way to combine the trained models into one "final" model?

Cheers, Thorsten

**Comment by Kamnitsask** [comment]
This is called ensembling. You should create a simple python script yourself, that loads the predictions of theirs, and somehow fuse them. Eg by averaging the class probability for each voxel across the models.

K
