### ISSUE TITLE
The Proper Command For Train Model Using The Previously Trained Model

### ISSUE THREAD

**Issue by ZeinabSalkhorde** [Kamnitsask/deepmedic#99]
Hi
Dear Mr. Kamnitsas
thanks for your great work and support.  Now I studied your high quality papers "DeepMedic for Brain Tumor Segmentation" and "Efficient Multi-Scale 3D CNN with Fully Connected CRF for Accurate Brain Lesion Segmentation". I used your software available at https://github.com/Kamnitsask/deepmedic. In this regard, I trained BRATS 2015 for the first time using this command:

 "./deepMedicRun -dev gpu -newModel ./examples/configFiles/deepMedic/model/modelConfig.cfg \
                           -train ./examples/configFiles/deepMedic/train/trainConfig.cfg"

, but now I want to train BRATS 2015 for the second time using the generated model of the first time. What command should I use instead of the above command.
,Very truly yours

Zeinab Salkhorde

**Comment by Kamnitsask** [comment]
Hello Zeinab,

Sorry for the late reply, I had a tough deadline 3 days ago and totally failed to follow these issues for a bit. Sorry for that.

What you want is easy. You can see the documentation at: https://github.com/Kamnitsask/deepmedic/blob/master/documentation/docTransferParamsResetOpt.md

You will need to use something like:

./deepMedicRun -dev gpu -train ./path/to/trainConfig/for/new/session -resetOptimizer -model ./path/to/previously/trained/model

The last path should point to your trained model, saved by default at ./examples/output/cnnModels/name/of/first/training/session/nameOfModel.NameOfTrainSession.final.date

Hope the above helps
